#!/usr/bin/env python3
"""Write zh-Hans.json and en.json from a single source of truth."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "Resources" / "Localization"

# key -> (zh, en)
STRINGS: dict[str, tuple[str, str]] = {
    # Language
    "language.system": ("跟随系统", "System"),
    "language.chinese": ("中文", "Chinese"),
    "language.english": ("English", "English"),

    # Tabs
    "tab.today": ("今日", "Today"),
    "tab.quests": ("任务", "Quests"),
    "tab.growth": ("成长", "Growth"),
    "tab.stats": ("统计", "Stats"),
    "tab.profile": ("我的", "Me"),

    # Common
    "common.cancel": ("取消", "Cancel"),
    "common.save": ("保存", "Save"),
    "common.done": ("完成", "Done"),
    "common.delete": ("删除", "Delete"),
    "common.edit": ("编辑", "Edit"),
    "common.ok": ("好", "OK"),
    "common.back": ("上一步", "Back"),
    "common.close": ("关闭", "Off"),
    "common.free": ("免费", "Free"),
    "common.max_level": ("已满级", "Max level"),
    "common.today": ("今天", "Today"),
    "common.tomorrow": ("明天", "Tomorrow"),
    "common.day_after": ("后天", "Day after"),
    "common.name": ("名称", "Name"),
    "common.icon": ("图标", "Icon"),
    "common.color": ("颜色", "Color"),
    "common.category": ("类别", "Category"),
    "common.basic": ("基本", "Basics"),
    "common.schedule": ("排期", "Schedule"),
    "common.skills": ("技能", "Skills"),
    "common.habits": ("习惯", "Habits"),
    "common.stats": ("属性", "Stats"),
    "common.reward": ("奖励", "Reward"),
    "common.difficulty": ("难度", "Difficulty"),
    "common.priority": ("优先级", "Priority"),
    "common.tags": ("标签", "Tags"),
    "common.data": ("数据", "Data"),
    "common.settings": ("设置", "Settings"),
    "common.shop": ("商店", "Shop"),
    "common.definition": ("定义", "Definition"),
    "common.domains": ("领域", "Domains"),
    "common.notice": ("提示", "Notice"),
    "common.yes": ("是", "Yes"),
    "common.no": ("否", "No"),
    "common.paused": ("已暂停", "Paused"),
    "common.pause": ("暂停", "Pause"),
    "common.enable": ("启用", "Enable"),
    "common.buy": ("购买", "Buy"),
    "common.use": ("使用", "Use"),
    "common.in_use": ("使用中", "In use"),
    "common.hidden": ("Hidden", "Hidden"),

    "date.md": ("%d月%d日", "%d/%d"),
    "weekday.short.1": ("日", "S"),
    "weekday.short.2": ("一", "M"),
    "weekday.short.3": ("二", "T"),
    "weekday.short.4": ("三", "W"),
    "weekday.short.5": ("四", "T"),
    "weekday.short.6": ("五", "F"),
    "weekday.short.7": ("六", "S"),
    "weekday.name.1": ("周日", "Sun"),
    "weekday.name.2": ("周一", "Mon"),
    "weekday.name.3": ("周二", "Tue"),
    "weekday.name.4": ("周三", "Wed"),
    "weekday.name.5": ("周四", "Thu"),
    "weekday.name.6": ("周五", "Fri"),
    "weekday.name.7": ("周六", "Sat"),

    "unit.count": ("个", ""),
    "unit.times": ("次", "x"),
    "unit.days": ("天", "d"),
    "unit.levels": ("级", "lv"),
    "unit.minutes": ("分钟", "min"),

    # Appearance
    "appearance.system": ("跟随系统", "System"),
    "appearance.light": ("浅色", "Light"),
    "appearance.dark": ("深色", "Dark"),

    # Quest kinds
    "quest.kind.main": ("主线", "Main"),
    "quest.kind.side": ("支线", "Side"),
    "quest.kind.repeating": ("重复", "Repeat"),
    "quest.difficulty.trivial": ("轻松", "Trivial"),
    "quest.difficulty.easy": ("简单", "Easy"),
    "quest.difficulty.normal": ("普通", "Normal"),
    "quest.difficulty.hard": ("困难", "Hard"),
    "quest.difficulty.epic": ("史诗", "Epic"),
    "quest.priority.lowest": ("最低", "Lowest"),
    "quest.priority.low": ("较低", "Low"),
    "quest.priority.normal": ("普通", "Normal"),
    "quest.priority.high": ("较高", "High"),
    "quest.priority.critical": ("最高", "Highest"),
    "quest.status.overdue": ("已延期", "Overdue"),
    "quest.status.overtime": ("已超时", "Overdue"),
    "quest.remaining.days": ("剩 %d 天", "%d d left"),
    "quest.remaining.hours": ("剩 %d 小时", "%d h left"),
    "quest.remaining.minutes": ("剩 %d 分钟", "%d min left"),
    "quest.complete": ("标记完成", "Complete"),
    "quest.uncomplete": ("撤销完成", "Undo complete"),
    "quest.move_tomorrow": ("挪到明天", "Move to tomorrow"),
    "quest.move_today": ("挪到今天", "Move to today"),
    "quest.delete": ("删除任务", "Delete quest"),
    "quest.detail.title": ("任务详情", "Quest detail"),
    "quest.scheduled": ("计划执行", "Scheduled"),
    "quest.created_on": ("创建于", "Created"),
    "quest.due_at": ("截止时间", "Due"),
    "quest.completed_at": ("完成于", "Completed"),
    "quest.estimated": ("预计时长", "Estimate"),
    "quest.minutes": ("%d 分钟", "%d min"),
    "quest.no_skills": ("未关联技能", "No skills linked"),
    "quest.exp_share": ("%d%% 经验", "%d%% XP"),
    "quest.reward_detail": ("奖励明细", "Reward breakdown"),
    "quest.base_exp": ("基础经验", "Base XP"),
    "quest.final_multiplier": ("最终乘数", "Final multiplier"),
    "quest.streak_bonus": ("连续加成", "Streak bonus"),
    "quest.total": ("合计", "Total"),
    "quest.new": ("新建任务", "New quest"),
    "quest.edit": ("编辑任务", "Edit quest"),
    "quest.title_placeholder": ("任务标题", "Quest title"),
    "quest.detail_placeholder": ("描述（可选）", "Notes (optional)"),
    "quest.tags_placeholder": ("标签，用空格分隔", "Tags, separated by spaces"),
    "quest.difficulty_priority": ("难度与优先级", "Difficulty & priority"),
    "quest.estimated_stepper": ("预计时长 %d 分钟", "Estimate %d min"),
    "quest.scheduled_day": ("计划执行日", "Scheduled day"),
    "quest.set_due": ("设置截止时间", "Set due time"),
    "quest.skill_share": ("技能经验分配", "Skill XP share"),
    "quest.reward_preview": ("预计奖励", "Estimated reward"),
    "quest.hint.planned": ("计划在今天之后 → 成为主线任务，获得 +20% 提前规划加成", "Scheduled after today → Main quest with +20% planning bonus"),
    "quest.hint.today": ("计划在今天 → 成为支线任务，奖励会打五折", "Scheduled today → Side quest at half reward"),
    "quest.publish": ("发布任务", "Post quest"),
    "quest.center": ("任务中心", "Quest hall"),
    "quest.view": ("视角", "View"),
    "quest.empty": ("还没有任务", "No quests yet"),
    "quest.empty.main": ("主线来自工会里张贴的计划委托", "Main quests come from planned guild contracts"),
    "quest.empty.side": ("支线是当天张贴的临时委托", "Side quests are same-day contracts"),
    "quest.empty.repeat": ("还没有重复任务", "No repeating quests yet"),
    "quest.empty.repeat.message": ("每天阅读、每周健身三次、每月总结，都可以在这里设置。", "Daily reading, weekly workouts, monthly reviews — set them here."),
    "quest.empty.repeat.action": ("创建周期任务", "Create repeating quest"),
    "quest.repeat.title": ("周期任务", "Repeating quests"),
    "quest.repeat.existing": ("已有的周期任务", "Existing repeating quests"),
    "quest.today_expired": ("%@（已过期）", "%@ (expired)"),
    "quest.challenge": ("挑战", "Challenges"),

    # Recurrence
    "recurrence.daily": ("每天", "Daily"),
    "recurrence.weekly": ("每周指定", "Weekly"),
    "recurrence.times_per_week": ("每周若干次", "Times per week"),
    "recurrence.monthly": ("每月", "Monthly"),
    "recurrence.every_n_days": ("每 %d 天", "Every %d days"),
    "recurrence.weekly_empty": ("每周", "Weekly"),
    "recurrence.weekday.prefix": ("周%@", "%@"),
    "recurrence.times": ("每周 %d 次", "%d times / week"),
    "recurrence.month_day": ("%d日", "%d"),
    "recurrence.monthly_empty": ("每月", "Monthly"),
    "recurrence.monthly_prefix": ("每月 %@", "Monthly %@"),
    "recurrence.this_period": ("从本周开始", "This week"),
    "recurrence.next_period": ("从下周开始", "Next week"),
    "recurrence.this_month": ("从本月开始", "This month"),
    "recurrence.next_month": ("从下月开始", "Next month"),
    "recurrence.from_today": ("从今天开始", "From today"),
    "recurrence.from_tomorrow": ("从明天开始", "From tomorrow"),
    "recurrence.section": ("重复规律", "Repeat rule"),
    "recurrence.mode": ("方式", "Mode"),
    "recurrence.every_n_stepper": ("每 %d 天一次", "Every %d days"),
    "recurrence.times_stepper": ("每周 %d 次", "%d times / week"),
    "recurrence.start": ("起算", "Start"),
    "recurrence.start_period": ("起算周期", "Start period"),
    "recurrence.start_footer": ("选择从下一周期开始，可以避免本周的进度被半途开始的记录拉低。", "Starting next period keeps this week's streak from being dragged down."),

    "longterm.recurrence": ("周期重复", "Repeating"),
    "longterm.range": ("一段时间", "Date range"),

    # Home / guild
    "home.title": ("今日冒险", "Today's adventure"),
    "home.calendar": ("告示日历", "Board calendar"),
    "home.publish": ("发布任务", "Post quest"),
    "home.guild": ("冒险者工会", "Adventurers' guild"),
    "home.board_today": ("今日任务栏", "Today's board"),
    "home.progress": ("完成 %d/%d", "%d/%d done"),
    "home.main.title": ("主线委托", "Main contracts"),
    "home.main.subtitle": ("计划中的冒险，完成 +20%", "Planned adventures, +20% reward"),
    "home.main.empty.title": ("告示板上还没有主线", "No main quests on the board"),
    "home.main.empty.message": ("发布计划任务，明天就能以主线身份领取更高报酬。", "Post a planned quest and collect the main-quest bonus tomorrow."),
    "home.main.empty.action": ("发布主线", "Post main quest"),
    "home.side.title": ("支线委托", "Side contracts"),
    "home.side.subtitle": ("今天的突发事项，报酬 -50%", "Same-day tasks, −50% reward"),
    "home.side.empty.title": ("暂时没有支线", "No side quests"),
    "home.side.empty.message": ("临时冒出来的事，可以立刻张贴到支线栏。", "Post sudden tasks here as side quests."),
    "home.side.empty.action": ("发布支线", "Post side quest"),
    "home.overdue.title": ("逾期委托", "Overdue contracts"),
    "home.overdue.subtitle": ("完成会有 -30% 惩罚，尽快处理或改期", "Completing these has a −30% penalty. Handle or reschedule them."),
    "home.habits.title": ("日常修炼", "Daily training"),
    "home.habits.subtitle": ("点一下就完成", "Tap to check in"),
    "home.habits.empty.title": ("还没有习惯", "No habits yet"),
    "home.habits.empty.message": ("习惯是最稳定的经验来源，去成长页添加一个。", "Habits are the steadiest XP source. Add one in Growth."),
    "home.report": ("今日战报", "Today's report"),
    "home.completion": ("完成率", "Completion"),
    "home.today_exp": ("今日EXP", "XP today"),
    "home.today_gold": ("今日金币", "Gold today"),
    "home.lucky": ("幸运日 · %@", "Lucky Day · %@"),
    "home.lucky.bonus": ("经验与金币 %@", "XP & gold %@"),
    "home.lucky.bonus_gold": ("经验与金币 %@，额外 +%d 金币", "XP & gold %@, extra +%d gold"),
    "header.day_n": ("第 %d 天", "Day %d"),
    "header.streak_next": ("再连续 %d 天可得 ×%.1f 加成", "%d more days for ×%.1f"),
    "header.streak_now": ("连续加成 ×%.1f", "Streak ×%.1f"),
    "gold.accessibility": ("金币 %d", "%d gold"),
    "gold.infinite": ("∞", "∞"),
    "gold.accessibility.infinite": ("无限金币", "Infinite gold"),
    "exp.to_next": ("距离下一级还差 %d EXP", "%d XP to next level"),
    "exp.progress": ("%d / %d EXP", "%d / %d XP"),

    # Publish wizard
    "wizard.cancel": ("取消", "Cancel"),
    "wizard.post": ("张贴委托", "Post contract"),
    "wizard.title.publish": ("发布任务", "Post quest"),
    "wizard.title.main_kind": ("主线形态", "Main quest type"),
    "wizard.title.repeat": ("周期委托", "Repeating contract"),
    "wizard.title.details": ("委托细节", "Contract details"),
    "wizard.step1.eyebrow": ("工会接待处 · 第一步", "Guild desk · Step 1"),
    "wizard.step1.title": ("冒险者，你要张贴什么委托？", "Adventurer, what contract are you posting?"),
    "wizard.step1.subtitle": ("主线是计划好的冒险，支线是今天突然冒出来的事。选错会影响报酬。", "Main quests are planned. Side quests are same-day surprises. The choice changes the reward."),
    "wizard.main.title": ("主线任务", "Main quest"),
    "wizard.main.subtitle": ("计划委托", "Planned contract"),
    "wizard.main.detail": ("安排在未来完成。到了那天自动成为主线，报酬 +20%。", "Schedule it for later. On that day it becomes a main quest with +20%."),
    "wizard.side.title": ("支线任务", "Side quest"),
    "wizard.side.subtitle": ("临时委托", "Same-day contract"),
    "wizard.side.detail": ("从今天开始、今天截止。适合突发事项，报酬会打五折。", "Starts and ends today. For sudden tasks, at half reward."),
    "wizard.step2.eyebrow": ("工会接待处 · 第二步", "Guild desk · Step 2"),
    "wizard.step2.title": ("这是长期委托，还是一次搞定？", "Is this a long-term contract, or a one-shot?"),
    "wizard.step2.subtitle": ("长期委托会按规律反复出现，紧急委托只需要完成一次。", "Long-term contracts repeat. Urgent ones are completed once."),
    "wizard.long.title": ("长期任务", "Long-term"),
    "wizard.long.subtitle": ("周期委托", "Repeating contract"),
    "wizard.long.detail": ("每天阅读、每周健身，或在一段日期内持续推进。", "Daily reading, weekly workouts, or a stretch of dates."),
    "wizard.urgent.title": ("紧急任务", "Urgent"),
    "wizard.urgent.subtitle": ("单次委托", "One-shot"),
    "wizard.urgent.detail": ("指定开始日期与当天截止时间，完成一次即可。", "Pick a start date and due time. Complete it once."),
    "wizard.field.title": ("委托名称", "Contract title"),
    "wizard.field.detail": ("描述（可选）", "Notes (optional)"),
    "wizard.notice": ("告示", "Notice"),
    "wizard.difficulty_section": ("任务难度", "Difficulty"),
    "wizard.skill_header": ("任务类型 · 技能经验", "Type · skill XP"),
    "wizard.skill_footer": ("所有技能共用 100%。拖动一项，其余技能会按比例填满剩余部分。", "Skills share 100%. Drag one and the rest fill the remainder."),
    "wizard.reward_section": ("预计报酬", "Estimated reward"),
    "wizard.type.side": ("支线 · 临时委托", "Side · same-day"),
    "wizard.type.urgent": ("主线 · 紧急单次", "Main · one-shot"),
    "wizard.type.long": ("主线 · 长期委托", "Main · long-term"),
    "wizard.start_today_fixed": ("今天（支线固定）", "Today (side quests only)"),
    "wizard.start_date": ("开始日期", "Start date"),
    "wizard.due_time": ("截止时间", "Due time"),
    "wizard.schedule": ("排期", "Schedule"),
    "wizard.hint.side": ("支线从今天开始，截止时间是今天的某个钟点。当天临时委托报酬 -50%。", "Side quests start today. Due time is a clock time today. Same-day reward −50%."),
    "wizard.hint.ahead": ("开始日在今天之后，将作为主线张贴，完成时 +20% 提前规划加成。", "A start date after today posts as a main quest with +20% planning bonus."),
    "wizard.hint.today_main": ("开始日是今天。仍会挂在主线栏，但按当天临时结算，报酬 -50%。想拿满加成，请改到明天。", "Start date is today. It stays on the main board but pays the same-day −50%. Move it to tomorrow for the full bonus."),
    "wizard.long_mode": ("排期方式", "Schedule mode"),
    "wizard.long_how": ("长期委托怎么排", "How to schedule the long-term quest"),
    "wizard.long_recurrence_footer": ("按规律自动生成实例，视同提前规划的主线。", "Instances generate automatically and count as planned main quests."),
    "wizard.long_range_footer": ("只张贴一条跨越多日的委托：从开始日挂到截止日，期间都会出现在任务栏上。", "Posts one spanning contract from start to due date. It stays on the board the whole time."),
    "wizard.set_end": ("设置结束日期", "Set end date"),
    "wizard.ends_on": ("结束于", "Ends on"),
    "wizard.until_when": ("持续到何时", "How long"),
    "wizard.no_end": ("不设结束日期就会一直按规律生成。", "With no end date, instances keep generating."),
    "wizard.end_date": ("截止日期", "End date"),
    "wizard.due_on_end": ("当天截止时间", "Due time that day"),
    "wizard.range_section": ("一段时间", "Date range"),
    "wizard.range_footer": ("委托会从开始日一直挂到截止日期。截止时间是截止日期当天的钟点。", "The contract stays from the start date through the due date. Due time is on the end day."),
    "wizard.base_reward": ("基础 %d EXP · %d 金币", "Base %d XP · %d gold"),

    # Planning calendar
    "planning.title": ("告示日历", "Board calendar"),
    "planning.which_day": ("查看哪天", "Which day"),
    "planning.custom_date": ("自定义日期", "Custom date"),
    "planning.target_day": ("目标日", "Target day"),
    "planning.day_quests": ("当天委托", "That day's contracts"),
    "planning.empty": ("这一天的告示板还是空的", "This day's board is empty"),
    "planning.repeat_preview": ("当天会自动生成的周期委托", "Repeating contracts that will generate"),
    "planning.repeat_footer": ("周期委托在当天开始时自动生成，视同提前规划的主线。", "Repeating contracts generate at day start and count as planned main quests."),
    "planning.hint.ahead": ("安排在未来的委托，到了那天会自动变成主线，并获得 +20% 提前规划加成。", "Future contracts become main quests that day, with +20% planning bonus."),
    "planning.hint.today": ("安排在今天的委托按当天临时结算，报酬会打五折。", "Contracts scheduled today pay the same-day half reward."),

    # Growth
    "growth.title": ("成长", "Growth"),
    "growth.view": ("视角", "View"),
    "growth.stats": ("属性", "Stats"),
    "growth.skills": ("技能", "Skills"),
    "growth.habits": ("习惯", "Habits"),
    "stat.philosophy": ("属性描述你正在成为怎样的人，技能描述你学会了什么。", "Stats describe who you are becoming. Skills describe what you have learned."),
    "stat.feeding": ("正在喂养这个属性的技能", "Skills feeding this stat"),
    "stat.feeding.empty": ("完成带有对应亲和度的技能任务，这个属性才会成长。幸运不能从这里训练。", "Complete quests with matching skill affinities to grow this stat. Luck cannot be trained here."),
    "lucky.today": ("今日命运：%@ · 经验与金币 %@", "Today's fortune: %@ · XP & gold %@"),
    "skill.empty.title": ("还没有技能", "No skills yet"),
    "skill.empty.message": ("技能占用栏位。开局有有限的栏位，升级后可以解锁更多。完成任务时把经验分配给它们。", "Skills take slots. You start with a few, and can unlock more by leveling up. Assign XP when you complete quests."),
    "skill.empty.action": ("创建技能", "Create skill"),
    "skill.unassigned": ("未分配属性", "Unassigned"),
    "skill.total_exp": ("总经验", "Total XP"),
    "skill.created": ("创建于", "Created"),
    "skill.affinity": ("属性亲和", "Stat affinity"),
    "skill.footer": ("完成任务时把经验分配给这个技能，它就会独立成长，并按亲和度喂养核心属性。幸运不能从技能训练。", "Assign quest XP to this skill and it grows on its own, feeding core stats by affinity. Luck cannot be trained from skills."),
    "skill.add": ("添加技能", "Add skill"),
    "skill.catalog": ("预设技能", "Presets"),
    "skill.custom": ("自定义", "Custom"),
    "skill.method": ("方式", "Method"),
    "skill.name_placeholder": ("例如 Origami、Archery", "e.g. Origami, Archery"),
    "skill.no_categories": ("目录里还没有类别", "No categories in the catalog"),
    "skill.affinity_footer": ("一个技能可以同时喂养多个核心属性，权重合计 100%。幸运不能从这里分配。", "A skill can feed several core stats. Weights must total 100%. Luck cannot be assigned here."),
    "skill.share_header": ("五个核心属性共用 100%", "Five core stats share 100%"),
    "skill.allocated": ("已分配 %d%%", "%d%% allocated"),
    "skill.no_share": ("还没有技能，先去成长页创建一个", "No skills yet. Create one in Growth first."),
    "skill.share_all": ("所有技能共用 100%", "All skills share 100%"),
    "skill.share_partial": ("经验分配", "XP share"),

    # Habits
    "habit.empty.title": ("还没有习惯", "No habits yet"),
    "habit.empty.message": ("阅读、喝水、运动、写日记……习惯是最稳定的经验来源。", "Reading, water, workouts, journaling — habits are the steadiest XP source."),
    "habit.empty.action": ("创建习惯", "Create habit"),
    "habit.new": ("新建习惯", "New habit"),
    "habit.name_placeholder": ("例如 阅读、喝水、冥想", "e.g. Reading, Water, Meditation"),
    "habit.icon_color": ("图标与颜色", "Icon & color"),
    "habit.daily_target": ("每日目标", "Daily target"),
    "habit.times_per_day": ("每天 %d 次", "%d times / day"),
    "habit.target_footer": ("奖励只在达成当日目标的那一次发放，所以把目标拆得更细不会拿到更多经验。", "Reward is granted only when the daily target is met, so splitting targets does not earn more XP."),
    "habit.reminder": ("提醒", "Reminder"),
    "habit.remind_daily": ("每天提醒", "Daily reminder"),
    "habit.time": ("时间", "Time"),
    "habit.days": ("天", "days"),
    "habit.best": ("最长连续 %d 天 · 累计 %d 次", "Best %d days · %d total"),
    "habit.last_30": ("最近 30 天", "Last 30 days"),
    "habit.times_value": ("%d 次", "%d times"),
    "habit.reminder_unset": ("未设置", "Not set"),
    "habit.check_again": ("今天再打一次卡", "Check in again today"),
    "habit.undo_today": ("撤销今天一次", "Undo one today"),
    "habit.fill_today": ("补满今天", "Fill today"),
    "habit.undo_once": ("撤销一次", "Undo one"),

    # Profile
    "profile.title": ("我的", "Me"),
    "profile.character": ("角色数据", "Character"),
    "profile.days_played": ("累计天数", "Days played"),
    "profile.login_streak": ("连续登录", "Login streak"),
    "profile.login_streak_value": ("%d 天（最长 %d 天）", "%d days (best %d)"),
    "profile.quests_done": ("完成任务", "Quests completed"),
    "profile.main_side": ("主线 / 支线", "Main / side"),
    "profile.habit_checkins": ("习惯打卡", "Habit check-ins"),
    "profile.habit_checkins_value": ("%d 次", "%d times"),
    "profile.perfect": ("完美达成", "Perfect days"),
    "profile.perfect_value": ("%d 天", "%d days"),
    "profile.lifetime": ("累计获得", "Lifetime gain"),
    "profile.core_stats": ("核心属性", "Core stats"),
    "profile.records": ("成长记录", "Progress"),
    "profile.achievements": ("成就", "Achievements"),
    "profile.titles": ("称号", "Titles"),
    "profile.challenges": ("挑战", "Challenges"),
    "profile.ledger": ("奖励流水", "Ledger"),
    "profile.shop": ("商店", "Shop"),
    "profile.settings": ("设置", "Settings"),

    "ledger.title": ("奖励流水", "Ledger"),
    "ledger.empty": ("还没有任何记录", "No records yet"),
    "ledger.reverted": ("已撤销", "Reverted"),

    "source.quest": ("任务", "Quest"),
    "source.habit": ("习惯", "Habit"),
    "source.challenge": ("挑战", "Challenge"),
    "source.achievement": ("成就", "Achievement"),
    "source.levelUp": ("升级", "Level up"),
    "source.streakBonus": ("连续奖励", "Streak bonus"),
    "source.purchase": ("购买", "Purchase"),
    "source.manual": ("手动调整", "Manual"),

    "unlock.kind.achievement": ("成就", "Achievement"),
    "unlock.kind.title": ("称号", "Title"),
    "unlock.kind.challenge": ("挑战", "Challenge"),
    "unlock.unlocked": ("已解锁", "Unlocked"),
    "unlock.obtained": ("已获得", "Earned"),
    "unlock.locked": ("未解锁", "Locked"),
    "unlock.unlocked_banner": ("%@解锁：%@", "%@ unlocked: %@"),
    "title.none": ("不佩戴称号", "No title"),
    "title.empty": ("还没有称号，去完成成就吧", "No titles yet. Earn some achievements."),
    "challenge.none": ("没有进行中的挑战", "No active challenges"),
    "challenge.ongoing": ("进行中", "In progress"),
    "challenge.footer": ("挑战是长期目标，进度由你的实际数据自动推导，不需要手动打勾。", "Challenges are long-term goals. Progress is derived from your real data — no manual checkmarks."),
    "challenge.completed": ("已完成", "Completed"),
    "challenge.custom": ("自定义挑战", "Custom challenge"),
    "challenge.name": ("挑战名称", "Challenge name"),
    "challenge.track": ("追踪什么", "What to track"),
    "challenge.any_skill": ("任意技能", "Any skill"),
    "challenge.any_habit": ("任意习惯", "Any habit"),
    "challenge.target": ("目标值", "Target"),
    "challenge.target_placeholder": ("目标", "Target"),
    "challenge.condition": ("达成条件", "Condition"),
    "challenge.condition_footer": ("挑战会持续对照你的真实数据自动判定，达成时自动结算奖励。", "The challenge watches your real data and pays out automatically when you hit the target."),
    "metric.totalQuestsCompleted": ("累计完成任务", "Quests completed"),
    "metric.totalMainQuestsCompleted": ("累计完成主线", "Main quests completed"),
    "metric.totalHabitCheckIns": ("累计打卡", "Habit check-ins"),
    "metric.bestLoginStreak": ("最长连续登录", "Best login streak"),
    "metric.playerLevel": ("玩家等级", "Player level"),
    "metric.totalStudyMinutes": ("累计学习时长", "Study time"),
    "metric.totalFocusMinutes": ("累计专注时长", "Focus time"),
    "metric.perfectDays": ("完美达成天数", "Perfect days"),
    "metric.skillLevel": ("指定技能等级", "Skill level"),
    "metric.habitStreak": ("指定习惯连续", "Habit streak"),

    # Stats page
    "stats.title": ("统计", "Statistics"),
    "stats.range": ("范围", "Range"),
    "stats.range.day": ("日", "Day"),
    "stats.range.week": ("周", "Week"),
    "stats.range.month": ("月", "Month"),
    "stats.range.year": ("年", "Year"),
    "stats.range.all": ("全部", "All"),
    "stats.overview": ("概览", "Overview"),
    "stats.completion": ("完成率", "Completion"),
    "stats.quests_done": ("完成任务", "Quests"),
    "stats.habit_checkins": ("习惯打卡", "Habits"),
    "stats.exp_earned": ("获得 EXP", "XP earned"),
    "stats.gold_earned": ("获得 Gold", "Gold earned"),
    "stats.active_days": ("活跃天数", "Active days"),
    "stats.avg_hours": ("任务从创建到完成平均耗时 %.1f 小时", "Average %.1f hours from create to complete"),
    "stats.daily_gain": ("每日获得", "Daily gain"),
    "stats.daily_gain_sub": ("经验与金币的产出节奏", "XP and gold cadence"),
    "stats.no_data": ("这个区间还没有数据", "No data in this range"),
    "stats.chart.date": ("日期", "Date"),
    "stats.main_side": ("主线与支线", "Main vs side"),
    "stats.main_side_sub": ("规划带来的结构变化", "How planning shapes the mix"),
    "stats.main_count": ("主线 %d", "Main %d"),
    "stats.side_count": ("支线 %d", "Side %d"),
    "stats.skill_curve": ("技能成长曲线", "Skill growth"),
    "stats.no_skills": ("还没有技能", "No skills yet"),
    "stats.skill": ("技能", "Skill"),
    "stats.level": ("等级", "Level"),
    "stats.heatmap": ("完成热力图", "Completion heatmap"),
    "stats.heatmap_sub": ("最近 26 周", "Last 26 weeks"),
    "stats.less": ("少", "Less"),
    "stats.more": ("多", "More"),
    "stats.mix.healthy": ("大部分产出来自提前规划的主线，节奏很健康。", "Most output comes from planned main quests. Healthy pace."),
    "stats.mix.mixed": ("主线与支线各占一半，试着把更多事情提前一天安排。", "Main and side are even. Try planning more things a day ahead."),
    "stats.mix.side": ("几乎全是当天临时任务，奖励被打了五折。规划一下明天会立刻见效。", "Almost everything is same-day. Rewards are halved. Plan tomorrow and it pays off immediately."),

    # Shop
    "shop.title": ("商店", "Shop"),
    "shop.kind": ("分类", "Category"),
    "shop.theme": ("主题", "Theme"),
    "shop.avatarFrame": ("头像框", "Frame"),
    "shop.background": ("背景", "Background"),
    "shop.effect": ("特效", "Effect"),
    "shop.sound": ("音效", "Sound"),
    "shop.pet": ("宠物", "Pet"),
    "shop.cannot_buy": ("无法购买", "Can't buy"),
    "shop.already_owned": ("已经拥有这件物品", "You already own this"),
    "shop.level_too_low": ("需要达到 Lv%d", "Requires Lv%d"),
    "shop.not_enough_gold": ("还差 %d 金币", "%d gold short"),
    "shop.buy_title": ("购买 %@", "Buy %@"),

    # Settings
    "settings.title": ("设置", "Settings"),
    "settings.language": ("语言", "Language"),
    "settings.language_footer": ("切换后界面立即更新。你自己起的任务、技能和习惯名称不会被翻译。", "The interface updates immediately. Names you typed for quests, skills, and habits stay as they are."),
    "settings.appearance": ("外观", "Appearance"),
    "settings.theme_mode": ("主题模式", "Appearance"),
    "settings.rpg_ui": ("RPG 风格界面", "RPG-styled UI"),
    "settings.color_theme": ("配色主题", "Color theme"),
    "settings.default_theme": ("默认", "Default"),
    "settings.time": ("时间", "Time"),
    "settings.day_start": ("一天从几点开始", "When the day starts"),
    "settings.carry_over": ("未完成的任务自动顺延", "Carry unfinished quests over"),
    "settings.time_footer": ("设为凌晨 4 点时，凌晨 1 点完成的任务仍然算作前一天。这个值会直接改变连续天数的统计口径，中途修改可能让某些连续记录看起来发生跳变。", "With a 4 AM day start, a 1 AM completion still counts as yesterday. This changes how streaks are counted; changing it mid-run can make streaks jump."),
    "settings.notifications": ("通知", "Notifications"),
    "settings.enable_notifications": ("启用本地通知", "Enable local notifications"),
    "settings.planning_reminder": ("明日规划提醒", "Tomorrow planning reminder"),
    "settings.reminder_time": ("提醒时间", "Reminder time"),
    "settings.bedtime": ("睡觉提醒", "Bedtime reminder"),
    "settings.bedtime_time": ("睡觉时间", "Bedtime"),
    "settings.request_permission": ("请求通知权限", "Request notification permission"),
    "settings.data": ("数据", "Data"),
    "settings.export_backup": ("导出完整备份（JSON）", "Export full backup (JSON)"),
    "settings.export_quests": ("导出任务（CSV）", "Export quests (CSV)"),
    "settings.export_daily": ("导出每日统计（CSV）", "Export daily stats (CSV)"),
    "settings.export_pdf": ("导出成长报告（PDF）", "Export growth report (PDF)"),
    "settings.restore": ("从备份恢复", "Restore from backup"),
    "settings.data_footer": ("恢复会先清空当前全部数据再写入备份内容，操作不可撤销。建议先导出一份当前备份。", "Restore wipes current data then writes the backup. This cannot be undone. Export a backup first."),
    "settings.testing": ("测试", "Testing"),
    "settings.shop_sandbox": ("解除商店限制并无限金币", "Unlock shop and infinite gold"),
    "settings.shop_sandbox_footer": ("仅用于测试。开启后商店不再检查等级，金币显示为无限，购买不扣真实余额。关闭后立即恢复原来的金币与解锁规则。", "For testing only. Shop ignores level gates, gold is treated as infinite, and purchases do not spend your real balance. Turning it off restores the original rules immediately."),
    "settings.diagnostics": ("配置诊断", "Config diagnostics"),
    "settings.about": ("关于", "About"),
    "settings.balance_version": ("平衡表版本", "Balance version"),
    "settings.rule_count": ("规则数量", "Rule count"),
    "settings.runtime": ("运行模式", "Runtime"),
    "settings.runtime.memory": ("内存（数据不会保留）", "In-memory (data will not persist)"),
    "settings.runtime.disk": ("本地持久化", "On-device persistence"),
    "settings.export_failed": ("导出失败：%@", "Export failed: %@"),
    "settings.restore_ok": ("恢复完成", "Restore complete"),
    "settings.restore_failed": ("恢复失败：%@", "Restore failed: %@"),
    "settings.account": ("账户", "Account"),
    "settings.reset": ("注销账户并清空存档", "Sign out and erase save"),
    "settings.reset_footer": ("会删除当前角色的全部进度、任务、技能和习惯，然后重新进入初始化流程。此操作不可撤销，建议先导出备份。", "Deletes this character's progress, quests, skills, and habits, then returns you to setup. This cannot be undone. Export a backup first."),
    "settings.reset.title": ("注销账户？", "Erase this save?"),
    "settings.reset.message": ("当前存档将被永久删除，你将以新的冒险者从头开始。", "This save will be permanently deleted. You will start over as a new adventurer."),
    "settings.reset.confirm": ("删除存档", "Delete save"),
    "settings.reset_failed": ("注销失败：%@", "Could not erase save: %@"),

    # Onboarding
    "onboarding.nav": ("冒险者登记", "Adventurer registry"),
    "onboarding.welcome": ("欢迎来到人生冒险", "Welcome to Life RPG"),
    "onboarding.step.title": ("称号", "Title"),
    "onboarding.step.skills": ("技能", "Skills"),
    "onboarding.title.subtitle": ("先给自己想一个冒险者称号。这是别人看到你时的名字，之后仍可在冒险中成长。", "First, invent an adventurer title. This is the name the world will know you by."),
    "onboarding.title.label": ("冒险者称号", "Adventurer title"),
    "onboarding.title.placeholder": ("例如：晨星旅人", "e.g. Dawn Traveler"),
    "onboarding.title.footer": ("最多 16 个字符。这是你的角色名，和之后解锁的佩戴称号不同。", "Up to 16 characters. This is your character name, separate from unlockable titles."),
    "onboarding.next": ("下一步", "Continue"),
    "onboarding.skills.hello": ("你好，%@", "Hello, %@"),
    "onboarding.skills.subtitle": ("从预设技能中挑选 0 到 %d 个你感兴趣的方向，也可以自定义。选定后将从零开始正式冒险。", "Pick 0 to %d skills from the catalog, or create your own. After this, the adventure starts from zero."),
    "onboarding.skills.selected": ("已选 %d / %d", "Selected %d / %d"),
    "onboarding.skills.count": ("已选 %d / %d 个技能", "%d / %d skills selected"),
    "onboarding.skills.custom": ("自定义技能", "Create a custom skill"),
    "onboarding.skills.custom_footer": ("自定义技能同样占用初始栏位。之后要学更多，需要升级解锁栏位，或先忘记一个技能。", "Custom skills also use a starting slot. Unlock more on level-up, or forget a skill later."),
    "onboarding.skills.full": ("初始栏位已经选满。去掉一个后才能再添加。", "Starting slots are full. Remove one to add another."),
    "onboarding.skills.skip_hint": ("一个都不选也可以。之后栏位有空时再学新技能。", "You can pick none and learn skills later when a slot is free."),
    "onboarding.start": ("开始冒险", "Begin adventure"),

    "skill.slots": ("技能栏位", "Skill slots"),
    "skill.slots.value": ("%d / %d", "%d / %d"),
    "skill.slots.hint": ("栏位满了之后，只能通过升级选择额外栏位，或删除已学技能来腾出位置。", "When slots are full, unlock more by leveling up or forget a skill to free one."),
    "skill.slots.full_hint": ("栏位已满。升级时选择额外栏位，或删除一个技能来学习新技能。", "Slots are full. Unlock more on level-up, or forget a skill to learn a new one."),
    "skill.slots.full": ("技能栏位已满（%d / %d）。先删除一个技能，或升级后选择额外栏位。", "Skill slots are full (%d / %d). Forget a skill, or unlock a slot on level-up."),
    "skill.quest_bonus": ("任务 +%d%%", "Quest +%d%%"),
    "skill.quest_bonus_label": ("关联任务奖励", "Quest reward bonus"),
    "skill.xp_bonus_label": ("技能经验增速", "Skill XP speed"),
    "skill.bonus_percent": ("+%d%%", "+%d%%"),
    "skill.delete.action": ("忘记这个技能", "Forget this skill"),
    "skill.delete.title": ("忘记技能？", "Forget this skill?"),
    "skill.delete.confirm": ("忘记并清空", "Forget"),
    "skill.delete.message": ("「%@」的 Lv%d 与全部经验会永久消失，栏位会空出来。此操作不可撤销。", "“%@” Lv%d and all of its XP will be erased, freeing the slot. This cannot be undone."),

    "stat.allocated": ("加点 +%d", "+%d allocated"),
    "stat.allocated_detail": ("加点 +%d · 训练等级 Lv%d", "+%d allocated · trained Lv%d"),
    "stat.effect": ("成长效果", "Growth effect"),
    "stat.effect.detail": ("匹配这个属性的技能经验加快 %d%%。", "Matching skills gain XP %d%% faster."),

    "levelup.title": ("升到 Lv%d", "Reached Lv%d"),
    "levelup.subtitle": ("金币已经入账。请再选一项额外奖励。", "Gold is already yours. Choose one extra reward."),
    "levelup.gold_already": ("金币奖励已发放", "Gold reward already granted"),
    "levelup.choice.stat": ("分配 1 点属性点", "Spend 1 stat point"),
    "levelup.choice.stat_detail": ("立刻加到五个核心属性之一，匹配技能的经验会涨得更快。", "Add it to one core stat. Matching skills will gain XP faster."),
    "levelup.choice.slot": ("解锁 1 个技能栏位", "Unlock 1 skill slot"),
    "levelup.choice.slot_detail": ("可掌握技能上限变为 %d。可以立刻学习，也可以留空。", "Skill cap becomes %d. Learn now or leave it empty."),
    "levelup.stat.current": ("当前 Lv%d", "Currently Lv%d"),
    "levelup.slot.unlocked": ("技能栏位已提升到 %d", "Skill cap is now %d"),
    "levelup.slot.followup": ("要现在学习新技能，还是把栏位留到以后？", "Learn a new skill now, or leave the slot empty?"),
    "levelup.slot.learn_now": ("立刻学习技能", "Learn a skill now"),
    "levelup.slot.later": ("稍后学习", "Learn later"),

    "reward.skill_level": ("技能等级 ×%.2f", "Skill level ×%.2f"),

    # Reminders / notifications
    "reminder.kind.quest": ("任务提醒", "Quest reminder"),
    "reminder.kind.habit": ("习惯提醒", "Habit reminder"),
    "reminder.kind.planning": ("明日规划提醒", "Planning reminder"),
    "reminder.kind.bedtime": ("睡觉提醒", "Bedtime reminder"),
    "reminder.kind.streak": ("连续签到提醒", "Streak reminder"),
    "reminder.kind.challenge": ("挑战提醒", "Challenge reminder"),
    "reminder.title.quest": ("任务到点了", "Quest is due"),
    "reminder.title.habit": ("该打卡了", "Time to check in"),
    "reminder.title.planning": ("规划明天的主线", "Plan tomorrow's main quests"),
    "reminder.title.bedtime": ("该休息了", "Time to rest"),
    "reminder.title.streak": ("别断了连续记录", "Don't break the streak"),
    "reminder.title.challenge": ("挑战进度检查", "Challenge check"),
    "notify.planning.body": ("花两分钟规划明天的主线，明天完成能多拿 20% 奖励", "Spend two minutes planning tomorrow's main quests for a +20% bonus"),
    "notify.bedtime.body": ("今天的冒险结束了，好好休息", "Today's adventure is over. Rest well."),

    # Celebration / fortune events
    "celebrate.level_up": ("升级！Lv%d", "Level up! Lv%d"),
    "celebrate.named_level": ("%@ 升到 Lv%d", "%@ reached Lv%d"),
    "celebrate.gold": ("获得 %d 金币", "Gained %d gold"),
    "fortune.event.lucky_day": ("幸运日 · %@", "Lucky Day · %@"),
    "fortune.event.bonus": ("经验与金币 %@", "XP & gold %@"),
    "fortune.event.bonus_gold": ("经验与金币 %@，额外 +%d 金币", "XP & gold %@, extra +%d gold"),
    "fortune.grew": ("幸运成长了", "Luck grew"),
    "fortune.level_up": ("幸运升到 Lv%d", "Luck reached Lv%d"),
    "fortune.xp": ("幸运 +%d EXP", "Luck +%d XP"),
    "reward.level_title": ("升级到 Lv%d", "Reached Lv%d"),
    "reward.level_breakdown": ("升级奖励 %d G", "Level-up reward %d G"),
    "reward.base": ("基础 %.0f", "Base %.0f"),
    "reward.duration": ("时长 ×%.2f", "Duration ×%.2f"),
    "reward.streak": ("连续 ×%.2f", "Streak ×%.2f"),

    # Config issues
    "config.missing": ("找不到配置文件 %@.json，已回退到内置默认值", "Missing %@.json, fell back to built-in defaults"),
    "config.parse": ("配置文件 %@.json 解析失败：%@", "Failed to parse %@.json: %@"),

    # Export
    "export.quests.header": ("日期,标题,类型,状态,难度,优先级,预计分钟,标签,完成时间,是否延期", "Date,Title,Type,Status,Difficulty,Priority,Minutes,Tags,Completed,Overdue"),
    "export.daily.header": ("日期,获得EXP,获得Gold,计划任务,完成任务,主线完成,支线完成,习惯打卡,习惯目标,完成率,专注分钟", "Date,XP,Gold,Planned,Completed,Main,Side,Habit check-ins,Habit targets,Completion,Focus minutes"),
    "export.pdf.title": ("Life RPG 成长报告", "Life RPG growth report"),
    "export.pdf.character": ("角色", "Character"),
    "export.pdf.nickname": ("昵称：%@", "Name: %@"),
    "export.pdf.level": ("等级：Lv%d（%d/%d EXP）", "Level: Lv%d (%d/%d XP)"),
    "export.pdf.gold": ("金币：%d", "Gold: %d"),
    "export.pdf.streak": ("连续登录：%d 天（最长 %d 天）", "Login streak: %d days (best %d)"),
    "export.pdf.days": ("累计天数：%d", "Days played: %d"),
    "export.pdf.quests": ("任务", "Quests"),
    "export.pdf.quests_done": ("累计完成：%d（主线 %d / 支线 %d）", "Completed: %d (main %d / side %d)"),
    "export.pdf.habits": ("习惯打卡：%d 次", "Habit check-ins: %d"),
    "export.pdf.perfect": ("完美达成天数：%d", "Perfect days: %d"),
    "export.pdf.skills": ("技能", "Skills"),
    "export.pdf.stats": ("统计", "Stats"),
    "export.pdf.records": ("有记录天数：%d，其中活跃 %d 天", "Recorded days: %d, active %d"),
    "export.pdf.lifetime": ("累计获得：%d EXP / %d Gold", "Lifetime: %d XP / %d Gold"),
    "export.pdf.exported": ("导出于 %@", "Exported %@"),

    # Core stats
    "stat.body.title": ("身体力", "Body"),
    "stat.mind.title": ("认知力", "Mind"),
    "stat.life.title": ("生活力", "Life"),
    "stat.social.title": ("社交力", "Social"),
    "stat.creation.title": ("创造力", "Creation"),
    "stat.body.summary": ("健康、体能、耐力与身体活动能力", "Health, fitness, endurance, and physical capability"),
    "stat.mind.summary": ("学习、理解、记忆、分析与知识积累", "Learning, reasoning, memory, and knowledge"),
    "stat.life.summary": ("管理时间、习惯、环境与日常事务的能力", "Managing time, habits, environment, and daily affairs"),
    "stat.social.summary": ("沟通、合作、表达与建立关系", "Communication, cooperation, expression, and relationships"),
    "stat.creation.summary": ("想象、设计、表达并把想法做成作品", "Imagination, design, expression, and making things"),
    "stat.body.definition": ("身体力代表身体健康、体能、力量、耐力、协调性以及身体活动能力。", "Body represents physical health, fitness, strength, endurance, coordination, and physical capability."),
    "stat.mind.definition": ("认知力代表学习、理解、记忆、分析、推理和知识积累能力。", "Mind represents the ability to learn, understand, remember, analyze, reason, and acquire knowledge."),
    "stat.life.definition": ("生活力代表一个人管理时间、习惯、环境、资源以及日常事务，并持续改善生活状态的综合能力。", "Life represents the ability to manage time, habits, environment, resources, and daily affairs, and to keep improving everyday living."),
    "stat.social.definition": ("社交力代表沟通、理解、合作、表达以及建立和维护人际关系的能力。", "Social represents the ability to communicate, understand, cooperate, express, and build relationships."),
    "stat.creation.definition": ("创造力代表想象、设计、表达以及把想法转化为实际作品的能力。", "Creation represents the ability to imagine, design, express, and turn ideas into something new."),
    "stat.lucky.title": ("幸运", "Lucky"),
    "stat.lucky.summary": ("命运的眷顾。不能训练，只能被惊喜点亮。", "Fortune's favor. It cannot be trained, only sparked as a surprise."),
    "stat.lucky.definition": ("幸运不是现实能力，而是命运对你的眷顾程度。无法主动分配，也无法直接训练。", "Luck is not a real-world skill. It is how much fate favors you. You cannot assign it or train it."),

    "stat.body.domain.0": ("力量", "Strength"),
    "stat.body.domain.1": ("耐力", "Endurance"),
    "stat.body.domain.2": ("心肺", "Cardio"),
    "stat.body.domain.3": ("柔韧", "Flexibility"),
    "stat.body.domain.4": ("协调", "Coordination"),
    "stat.body.domain.5": ("运动能力", "Athletics"),
    "stat.body.domain.6": ("身体健康", "Health"),
    "stat.mind.domain.0": ("学习", "Learning"),
    "stat.mind.domain.1": ("知识", "Knowledge"),
    "stat.mind.domain.2": ("逻辑", "Logic"),
    "stat.mind.domain.3": ("记忆", "Memory"),
    "stat.mind.domain.4": ("语言", "Language"),
    "stat.mind.domain.5": ("研究", "Research"),
    "stat.mind.domain.6": ("分析", "Analysis"),
    "stat.mind.domain.7": ("阅读", "Reading"),
    "stat.life.domain.0": ("自律", "Discipline"),
    "stat.life.domain.1": ("时间管理", "Time management"),
    "stat.life.domain.2": ("组织管理", "Organization"),
    "stat.life.domain.3": ("日常生活", "Daily living"),
    "stat.life.domain.4": ("财务管理", "Finance"),
    "stat.life.domain.5": ("独立生活", "Independence"),
    "stat.social.domain.0": ("沟通", "Communication"),
    "stat.social.domain.1": ("表达", "Expression"),
    "stat.social.domain.2": ("倾听", "Listening"),
    "stat.social.domain.3": ("合作", "Cooperation"),
    "stat.social.domain.4": ("领导", "Leadership"),
    "stat.social.domain.5": ("谈判", "Negotiation"),
    "stat.social.domain.6": ("社交", "Socializing"),
    "stat.social.domain.7": ("人际关系", "Relationships"),
    "stat.creation.domain.0": ("艺术", "Art"),
    "stat.creation.domain.1": ("设计", "Design"),
    "stat.creation.domain.2": ("写作", "Writing"),
    "stat.creation.domain.3": ("音乐", "Music"),
    "stat.creation.domain.4": ("游戏开发", "Game development"),
    "stat.creation.domain.5": ("摄影", "Photography"),
    "stat.creation.domain.6": ("视频", "Video"),
    "stat.creation.domain.7": ("手工", "Craft"),

    # Fortune
    "fortune.fortune_1.name": ("小吉", "Fortune I"),
    "fortune.fortune_2.name": ("中吉", "Fortune II"),
    "fortune.fortune_3.name": ("大吉", "Fortune III"),
    "fortune.fortune_4.name": ("天命", "Fortune IV"),

    # Modifiers
    "modifier.planned_ahead.label": ("提前规划", "Planned ahead"),
    "modifier.same_day.label": ("当天临时", "Same day"),
    "modifier.on_time.label": ("按时完成", "On time"),
    "modifier.overdue.label": ("延期完成", "Overdue"),
    "modifier.five_star.label": ("五星任务", "Five-star"),
    "modifier.consecutive.label": ("连续完成", "Streak"),

    # Skill categories
    "skill.category.fitness": ("体能", "Fitness"),
    "skill.category.knowledge": ("知识", "Knowledge"),
    "skill.category.language": ("语言", "Language"),
    "skill.category.discipline": ("自律", "Discipline"),
    "skill.category.time": ("时间", "Time"),
    "skill.category.organization": ("组织", "Organization"),
    "skill.category.daily_living": ("日常", "Daily living"),
    "skill.category.finance": ("财务", "Finance"),
    "skill.category.independence": ("独立", "Independence"),
    "skill.category.communication": ("沟通", "Communication"),
    "skill.category.leadership": ("领导", "Leadership"),
    "skill.category.art": ("艺术", "Art"),
    "skill.category.design": ("设计", "Design"),
    "skill.category.media": ("影像", "Media"),
    "skill.category.craft": ("手作", "Craft"),
}

SKILLS = {
    "running": ("跑步", "Running"),
    "swimming": ("游泳", "Swimming"),
    "walking": ("步行", "Walking"),
    "cycling": ("骑行", "Cycling"),
    "hiking": ("徒步", "Hiking"),
    "strength_training": ("力量训练", "Strength Training"),
    "yoga": ("瑜伽", "Yoga"),
    "dancing": ("舞蹈", "Dancing"),
    "martial_arts": ("武术", "Martial Arts"),
    "reading": ("阅读", "Reading"),
    "studying": ("学习", "Studying"),
    "programming": ("编程", "Programming"),
    "mathematics": ("数学", "Mathematics"),
    "japanese": ("日语", "Japanese"),
    "english": ("英语", "English"),
    "research": ("研究", "Research"),
    "writing": ("写作", "Writing"),
    "habit_building": ("习惯养成", "Habit Building"),
    "planning": ("规划", "Planning"),
    "task_management": ("任务管理", "Task Management"),
    "cooking": ("烹饪", "Cooking"),
    "cleaning": ("打扫", "Cleaning"),
    "budgeting": ("记账", "Budgeting"),
    "conversation": ("交谈", "Conversation"),
    "public_speaking": ("演讲", "Public Speaking"),
    "listening": ("倾听", "Listening"),
    "negotiation": ("谈判", "Negotiation"),
    "teamwork": ("协作", "Teamwork"),
    "leadership": ("领导力", "Leadership"),
    "drawing": ("绘画", "Drawing"),
    "music": ("音乐", "Music"),
    "photography": ("摄影", "Photography"),
    "design": ("设计", "Design"),
    "game_development": ("游戏开发", "Game Development"),
    "video_editing": ("视频剪辑", "Video Editing"),
    "crafting": ("手工", "Crafting"),
}

SHOP = {
    "theme_default": ("起始之地", "Starting Land", "默认主题", "Default theme"),
    "theme_forest": ("翡翠密林", "Jade Forest", "沉静的绿色调", "Calm greens"),
    "theme_ember": ("余烬熔炉", "Ember Forge", "炽热的橙红色调", "Ember oranges"),
    "theme_midnight": ("午夜星轨", "Midnight Orbit", "深邃的靛蓝色调", "Deep indigo"),
    "theme_sakura": ("落樱庭院", "Sakura Court", "柔和的粉色调", "Soft pinks"),
    "theme_gold": ("黄金王座", "Golden Throne", "传说级配色", "Legendary palette"),
    "frame_bronze": ("青铜边框", "Bronze Frame", "朴素而可靠", "Plain and reliable"),
    "frame_silver": ("白银边框", "Silver Frame", "微光流转", "Soft gleam"),
    "frame_gold": ("黄金边框", "Gold Frame", "耀眼夺目", "Dazzling"),
    "frame_mythic": ("秘境边框", "Mythic Frame", "只属于传说", "For legends only"),
    "bg_parchment": ("羊皮卷", "Parchment", "冒险者的手札", "An adventurer's journal"),
    "bg_aurora": ("极光", "Aurora", "北境之光", "Northern lights"),
    "fx_levelup_burst": ("升级光爆", "Level Burst", "升级时的粒子特效", "Level-up particles"),
    "fx_complete_spark": ("完成火花", "Completion Spark", "完成任务时的火花", "Sparks on quest complete"),
    "sfx_classic": ("经典音效包", "Classic SFX", "复古 RPG 提示音", "Classic RPG cues"),
    "pet_slime": ("史莱姆", "Slime", "会在首页跟着你", "Follows you on Home"),
    "pet_owl": ("学者猫头鹰", "Scholar Owl", "深夜的伙伴", "A late-night companion"),
}

UNLOCKS = {
    "ach_first_quest": ("第一步", "First Step", "完成你的第一个任务", "Complete your first quest"),
    "ach_quest_100": ("百战", "Centurion", "累计完成 100 个任务", "Complete 100 quests"),
    "ach_quest_1000": ("千锤百炼", "Tempered", "累计完成 1000 个任务", "Complete 1000 quests"),
    "ach_main_50": ("主线推进者", "Mainline", "累计完成 50 个主线任务", "Complete 50 main quests"),
    "ach_habit_100": ("习惯的力量", "Habit Power", "累计打卡 100 次", "Check in 100 times"),
    "ach_login_7": ("一周不辍", "Week Unbroken", "连续登录 7 天", "Log in 7 days in a row"),
    "ach_login_30": ("月度坚守", "Monthly Vigil", "连续登录 30 天", "Log in 30 days in a row"),
    "ach_login_100": ("百日之约", "Hundred Days", "连续登录 100 天", "Log in 100 days in a row"),
    "ach_skill_50": ("专精", "Specialist", "任意技能达到 Lv50", "Any skill reaches Lv50"),
    "ach_skill_100": ("宗师", "Grandmaster", "任意技能达到 Lv100", "Any skill reaches Lv100"),
    "ach_player_25": ("初露锋芒", "First Edge", "玩家等级达到 Lv25", "Reach player Lv25"),
    "ach_focus_100h": ("百小时法则", "100-Hour Rule", "累计专注 100 小时", "Focus for 100 hours"),
    "ach_early_bird": ("破晓", "Daybreak", "在早上 6 点前完成一个任务", "Complete a quest before 6 AM"),
    "ach_night_owl": ("深夜行者", "Night Walker", "在凌晨 1 点后完成一个任务", "Complete a quest after 1 AM"),
    "ach_perfect_10": ("完美主义", "Perfectionist", "累计 10 个完成率 100% 的日子", "10 days at 100% completion"),
    "title_programmer": ("Programmer", "Programmer", "Programming 技能达到 Lv20", "Programming reaches Lv20"),
    "title_scholar": ("Scholar", "Scholar", "累计学习 50 小时", "Study for 50 hours"),
    "title_warrior": ("Warrior", "Warrior", "Fitness 技能达到 Lv20", "Fitness reaches Lv20"),
    "title_artist": ("Artist", "Artist", "Drawing 技能达到 Lv20", "Drawing reaches Lv20"),
    "title_explorer": ("Explorer", "Explorer", "连续登录 100 天", "Log in 100 days in a row"),
    "title_night_owl": ("Night Owl", "Night Owl", "在凌晨完成任务", "Complete a quest after midnight"),
    "title_early_bird": ("Early Bird", "Early Bird", "在清晨完成任务", "Complete a quest in the morning"),
    "title_legend": ("Legend", "Legend", "玩家等级达到 Lv60", "Reach player Lv60"),
    "chal_read_100_days": ("连续阅读 100 天", "Read 100 Days", "保持阅读习惯连续 100 天", "Keep a reading streak of 100 days"),
    "chal_study_100h": ("完成 100 小时学习", "Study 100 Hours", "累计学习时长达到 100 小时", "Accumulate 100 hours of study"),
    "chal_quest_365": ("一年 365 个任务", "365 Quests", "累计完成 365 个任务", "Complete 365 quests"),
    "chal_fitness_lv30": ("健身达人", "Fitness Ace", "Fitness 技能达到 Lv30", "Fitness reaches Lv30"),
    "chal_habit_1000": ("千次打卡", "Thousand Check-ins", "累计打卡 1000 次", "Check in 1000 times"),
}


def main() -> None:
    table = dict(STRINGS)
    for sid, (zh, en) in SKILLS.items():
        table[f"skill.{sid}.name"] = (zh, en)
    for sid, (zh_name, en_name, zh_detail, en_detail) in SHOP.items():
        table[f"shop.{sid}.name"] = (zh_name, en_name)
        table[f"shop.{sid}.detail"] = (zh_detail, en_detail)
    for sid, (zh_name, en_name, zh_detail, en_detail) in UNLOCKS.items():
        table[f"unlock.{sid}.name"] = (zh_name, en_name)
        table[f"unlock.{sid}.detail"] = (zh_detail, en_detail)

    OUT.mkdir(parents=True, exist_ok=True)
    zh = {k: v[0] for k, v in table.items()}
    en = {k: v[1] for k, v in table.items()}
    for name, data in (("zh-Hans.json", zh), ("en.json", en)):
        path = OUT / name
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        print(f"wrote {path} ({len(data)} keys)")


if __name__ == "__main__":
    main()
