#!/usr/bin/env python3
"""Write zh-Hans.json and en.json from a single source of truth."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "Resources" / "Localization"

# key -> (zh, en)
STRINGS: dict[str, tuple[str, str]] = {
    # Language
    "language.system": ("跟随系统", "System"),
    "language.chinese": ("中文", "Chinese"),
    "language.english": ("English", "English"),

    # Tabs
    "tab.today": ("今日", "Today"),
    "tab.quests": ("任务", "Quests"),
    "tab.growth": ("成长", "Growth"),
    "tab.stats": ("统计", "Stats"),
    "tab.profile": ("我的", "Me"),

    # Common
    "common.cancel": ("取消", "Cancel"),
    "common.save": ("保存", "Save"),
    "common.done": ("完成", "Done"),
    "common.delete": ("删除", "Delete"),
    "common.edit": ("编辑", "Edit"),
    "common.ok": ("好", "OK"),
    "common.back": ("上一步", "Back"),
    "common.close": ("关闭", "Off"),
    "common.free": ("免费", "Free"),
    "common.max_level": ("已满级", "Max level"),
    "common.today": ("今天", "Today"),
    "common.tomorrow": ("明天", "Tomorrow"),
    "common.day_after": ("后天", "Day after"),
    "common.name": ("名称", "Name"),
    "common.icon": ("图标", "Icon"),
    "common.color": ("颜色", "Color"),
    "common.category": ("类别", "Category"),
    "common.basic": ("基本", "Basics"),
    "common.schedule": ("排期", "Schedule"),
    "common.skills": ("技能", "Skills"),
    "common.habits": ("习惯", "Habits"),
    "common.stats": ("属性", "Stats"),
    "common.reward": ("奖励", "Reward"),
    "common.difficulty": ("难度", "Difficulty"),
    "common.priority": ("优先级", "Priority"),
    "common.tags": ("标签", "Tags"),
    "common.data": ("数据", "Data"),
    "common.settings": ("设置", "Settings"),
    "common.shop": ("商店", "Shop"),
    "common.definition": ("定义", "Definition"),
    "common.domains": ("领域", "Domains"),
    "common.notice": ("提示", "Notice"),
    "common.yes": ("是", "Yes"),
    "common.no": ("否", "No"),
    "common.paused": ("已暂停", "Paused"),
    "common.pause": ("暂停", "Pause"),
    "common.enable": ("启用", "Enable"),
    "common.buy": ("购买", "Buy"),
    "common.use": ("使用", "Use"),
    "common.in_use": ("使用中", "In use"),
    "common.unequip": ("卸下", "Unequip"),
    "common.hidden": ("Hidden", "Hidden"),

    "date.md": ("%d月%d日", "%d/%d"),
    "weekday.short.1": ("日", "S"),
    "weekday.short.2": ("一", "M"),
    "weekday.short.3": ("二", "T"),
    "weekday.short.4": ("三", "W"),
    "weekday.short.5": ("四", "T"),
    "weekday.short.6": ("五", "F"),
    "weekday.short.7": ("六", "S"),
    "weekday.name.1": ("周日", "Sun"),
    "weekday.name.2": ("周一", "Mon"),
    "weekday.name.3": ("周二", "Tue"),
    "weekday.name.4": ("周三", "Wed"),
    "weekday.name.5": ("周四", "Thu"),
    "weekday.name.6": ("周五", "Fri"),
    "weekday.name.7": ("周六", "Sat"),

    "unit.count": ("个", ""),
    "unit.times": ("次", "x"),
    "unit.days": ("天", "d"),
    "unit.levels": ("级", "lv"),
    "unit.minutes": ("分钟", "min"),

    # Appearance
    "appearance.system": ("跟随系统", "System"),
    "appearance.light": ("浅色", "Light"),
    "appearance.dark": ("深色", "Dark"),

    # Quest kinds
    "quest.kind.main": ("主线", "Main"),
    "quest.kind.side": ("支线", "Side"),
    "quest.kind.repeating": ("重复", "Repeat"),
    "quest.difficulty.trivial": ("轻松", "Trivial"),
    "quest.difficulty.easy": ("简单", "Easy"),
    "quest.difficulty.normal": ("普通", "Normal"),
    "quest.difficulty.hard": ("困难", "Hard"),
    "quest.difficulty.epic": ("史诗", "Epic"),
    "quest.priority.lowest": ("最低", "Lowest"),
    "quest.priority.low": ("较低", "Low"),
    "quest.priority.normal": ("普通", "Normal"),
    "quest.priority.high": ("较高", "High"),
    "quest.priority.critical": ("最高", "Highest"),
    "quest.status.overdue": ("已延期", "Overdue"),
    "quest.status.overtime": ("已超时", "Overdue"),
    "quest.remaining.days": ("剩 %d 天", "%d d left"),
    "quest.remaining.hours": ("剩 %d 小时", "%d h left"),
    "quest.remaining.minutes": ("剩 %d 分钟", "%d min left"),
    "quest.complete": ("标记完成", "Complete"),
    "quest.uncomplete": ("撤销完成", "Undo complete"),
    "quest.move_tomorrow": ("挪到明天", "Move to tomorrow"),
    "quest.move_today": ("挪到今天", "Move to today"),
    "quest.delete": ("删除任务", "Delete quest"),
    "quest.detail.title": ("任务详情", "Quest detail"),
    "quest.scheduled": ("计划执行", "Scheduled"),
    "quest.created_on": ("创建于", "Created"),
    "quest.due_at": ("截止时间", "Due"),
    "quest.completed_at": ("完成于", "Completed"),
    "quest.estimated": ("预计时长", "Estimate"),
    "quest.minutes": ("%d 分钟", "%d min"),
    "quest.no_skills": ("未关联技能", "No skills linked"),
    "quest.exp_share": ("%d%% 经验", "%d%% XP"),
    "quest.reward_detail": ("奖励明细", "Reward breakdown"),
    "quest.base_exp": ("基础经验", "Base XP"),
    "quest.final_multiplier": ("最终乘数", "Final multiplier"),
    "quest.streak_bonus": ("连续加成", "Streak bonus"),
    "quest.total": ("合计", "Total"),
    "quest.new": ("新建任务", "New quest"),
    "quest.edit": ("编辑任务", "Edit quest"),
    "quest.title_placeholder": ("任务标题", "Quest title"),
    "quest.detail_placeholder": ("描述（可选）", "Notes (optional)"),
    "quest.tags_placeholder": ("标签，用空格分隔", "Tags, separated by spaces"),
    "quest.difficulty_priority": ("难度与优先级", "Difficulty & priority"),
    "quest.difficulty": ("难度", "Difficulty"),
    "quest.priority": ("优先级", "Priority"),
    "quest.difficulty.auto_footer": ("难度随预计时长自动变化，时长越长基础奖励越高。优先级请按事情的紧急程度自己选。", "Difficulty follows the time estimate: longer tasks give a higher base reward. Set priority yourself by urgency."),
    "quest.estimated_stepper": ("预计时长 %d 分钟", "Estimate %d min"),
    "quest.scheduled_day": ("计划执行日", "Scheduled day"),
    "quest.set_due": ("设置截止时间", "Set due time"),
    "quest.skill_share": ("技能经验分配", "Skill XP share"),
    "quest.reward_preview": ("预计奖励", "Estimated reward"),
    "quest.hint.planned": ("计划在今天之后 → 成为主线任务，获得 +20% 提前规划加成", "Scheduled after today → Main quest with +20% planning bonus"),
    "quest.hint.today": ("计划在今天 → 成为支线任务，奖励 -20%", "Scheduled today → Side quest at −20% reward"),
    "quest.publish": ("发布任务", "Post quest"),
    "quest.center": ("任务中心", "Quest hall"),
    "quest.view": ("视角", "View"),
    "quest.empty": ("还没有任务", "No quests yet"),
    "quest.empty.main": ("主线来自工会里张贴的计划委托", "Main quests come from planned guild contracts"),
    "quest.empty.side": ("支线是当天张贴的临时委托", "Side quests are same-day contracts"),
    "quest.empty.repeat": ("还没有重复任务", "No repeating quests yet"),
    "quest.empty.repeat.message": ("每天阅读、每周健身三次、每月总结，都可以在这里设置。", "Daily reading, weekly workouts, monthly reviews — set them here."),
    "quest.empty.repeat.action": ("创建周期任务", "Create repeating quest"),
    "quest.repeat.title": ("周期任务", "Repeating quests"),
    "quest.repeat.existing": ("已有的周期任务", "Existing repeating quests"),
    "quest.finish": ("收队", "Come home"),
    "quest.finish.title": ("结束这段旅途", "End this journey"),
    "quest.finish.series": ("结束整趟远行", "End this expedition"),
    "quest.finish.action": ("确认收队", "Confirm return"),
    "quest.finish.message": ("【%@】走了 %d 天，途中完成 %d 次。\n归途奖励：%d EXP / %d G。\n收队后不再生成新任务。", "[%@] ran for %d days with %d stops along the way.\nHomecoming reward: %d EXP / %d G.\nNo new quests will be generated."),
    "quest.finished": ("已归途", "Returned"),
    "quest.finish.days": ("%d 天", "%d d"),
    "quest.journey.count": ("%d 段旅途", "%d legs"),
    "quest.finish.tier.spark": ("初程", "First road"),
    "quest.finish.tier.proven": ("短途", "Short road"),
    "quest.finish.tier.veteran": ("远行", "Long road"),
    "quest.finish.tier.legendary": ("长旅", "Grand tour"),
    "quest.finish.tier.mythic": ("环岁", "Year road"),
    "quest.today_expired": ("%@（已过期）", "%@ (expired)"),
    "quest.challenge": ("挑战", "Challenges"),

    # Recurrence
    "recurrence.daily": ("每天", "Daily"),
    "recurrence.weekly": ("每周指定", "Weekly"),
    "recurrence.times_per_week": ("每周若干次", "Times per week"),
    "recurrence.monthly": ("每月", "Monthly"),
    "recurrence.every_n_days": ("每 %d 天", "Every %d days"),
    "recurrence.weekly_empty": ("每周", "Weekly"),
    "recurrence.weekday.prefix": ("周%@", "%@"),
    "recurrence.times": ("每周 %d 次", "%d times / week"),
    "recurrence.month_day": ("%d日", "%d"),
    "recurrence.monthly_empty": ("每月", "Monthly"),
    "recurrence.monthly_prefix": ("每月 %@", "Monthly %@"),
    "recurrence.this_period": ("从本周开始", "This week"),
    "recurrence.next_period": ("从下周开始", "Next week"),
    "recurrence.this_month": ("从本月开始", "This month"),
    "recurrence.next_month": ("从下月开始", "Next month"),
    "recurrence.from_today": ("从今天开始", "From today"),
    "recurrence.from_tomorrow": ("从明天开始", "From tomorrow"),
    "recurrence.section": ("重复规律", "Repeat rule"),
    "recurrence.mode": ("方式", "Mode"),
    "recurrence.every_n_stepper": ("每 %d 天一次", "Every %d days"),
    "recurrence.times_stepper": ("每周 %d 次", "%d times / week"),
    "recurrence.daily_cap_stepper": ("每天最多 %d 次", "At most %d / day"),
    "recurrence.start": ("起算", "Start"),
    "recurrence.start_period": ("起算周期", "Start period"),
    "recurrence.start_footer": ("选择从下一周期开始，可以避免本周的进度被半途开始的记录拉低。", "Starting next period keeps this week's streak from being dragged down."),

    "longterm.recurrence": ("周期重复", "Repeating"),
    "longterm.range": ("一段时间", "Date range"),

    # Home / guild
    "home.title": ("今日冒险", "Today's adventure"),
    "home.calendar": ("告示日历", "Board calendar"),
    "home.publish": ("发布任务", "Post quest"),
    "home.guild": ("冒险者工会", "Adventurers' guild"),
    "home.board_today": ("今日任务栏", "Today's board"),
    "home.progress": ("完成 %d/%d", "%d/%d done"),
    "home.filter.all": ("全部任务", "All quests"),
    "home.filter.main": ("主线任务", "Main quests"),
    "home.filter.side": ("支线任务", "Side quests"),
    "home.count.main": ("主线", "Main"),
    "home.count.side": ("支线", "Side"),
    "home.count.habits": ("日常修行", "Training"),
    "home.count.fraction": ("%d/%d", "%d/%d"),
    "home.reward.today": ("今日奖励", "Today's rewards"),
    "home.reward.summary": ("+%d EXP  +%d G", "+%d XP  +%d G"),
    "home.empty.all.title": ("告示板上还没有任务", "No quests on the board"),
    "home.empty.all.message": ("发布一条主线或支线，开始今天的冒险。", "Post a main or side quest to start today's adventure."),
    "home.empty.all.action": ("发布任务", "Post quest"),
    "home.main.title": ("主线委托", "Main contracts"),
    "home.main.subtitle": ("计划中的冒险，完成 +20%", "Planned adventures, +20% reward"),
    "home.main.empty.title": ("告示板上还没有主线", "No main quests on the board"),
    "home.main.empty.message": ("发布计划任务，明天就能以主线身份领取更高报酬。", "Post a planned quest and collect the main-quest bonus tomorrow."),
    "home.main.empty.action": ("发布主线", "Post main quest"),
    "home.side.title": ("支线委托", "Side contracts"),
    "home.side.subtitle": ("今天的突发事项，报酬 -20%", "Same-day tasks, −20% reward"),
    "home.side.empty.title": ("暂时没有支线", "No side quests"),
    "home.side.empty.message": ("临时冒出来的事，可以立刻张贴到支线栏。", "Post sudden tasks here as side quests."),
    "home.side.empty.action": ("发布支线", "Post side quest"),
    "home.overdue.title": ("逾期委托", "Overdue contracts"),
    "home.overdue.subtitle": ("完成会有 -50% 惩罚，尽快处理或改期", "Completing these has a −50% penalty. Handle or reschedule them."),
    "home.habits.title": ("日常修炼", "Daily training"),
    "home.habits.subtitle": ("点一下就完成", "Tap to check in"),
    "home.habits.empty.title": ("还没有习惯", "No habits yet"),
    "home.habits.empty.message": ("习惯是最稳定的经验来源，去成长页添加一个。", "Habits are the steadiest XP source. Add one in Growth."),
    "home.report": ("今日战报", "Today's report"),
    "home.completion": ("完成率", "Completion"),
    "home.today_exp": ("今日EXP", "XP today"),
    "home.today_gold": ("今日金币", "Gold today"),
    "home.lucky": ("幸运日 · %@", "Lucky Day · %@"),
    "home.lucky.bonus": ("经验与金币 %@", "XP & gold %@"),
    "home.lucky.bonus_gold": ("经验与金币 %@，额外 +%d 金币", "XP & gold %@, extra +%d gold"),
    "header.day_n": ("第 %d 天", "Day %d"),
    "header.streak_next": ("再连续 %d 天可得 ×%.1f 加成", "%d more days for ×%.1f"),
    "header.streak_now": ("连续加成 ×%.1f", "Streak ×%.1f"),
    "gold.accessibility": ("金币 %d", "%d gold"),
    "gold.infinite": ("∞", "∞"),
    "gold.accessibility.infinite": ("无限金币", "Infinite gold"),
    "exp.to_next": ("距离下一级还差 %d EXP", "%d XP to next level"),
    "exp.progress": ("%d / %d EXP", "%d / %d XP"),

    # Publish wizard
    "wizard.cancel": ("取消", "Cancel"),
    "wizard.post": ("张贴委托", "Post contract"),
    "wizard.title.publish": ("发布任务", "Post quest"),
    "wizard.title.main_kind": ("主线形态", "Main quest type"),
    "wizard.title.repeat": ("周期委托", "Repeating contract"),
    "wizard.title.details": ("委托细节", "Contract details"),
    "wizard.title.side": ("贴支线", "Side quest"),
    "wizard.step1.eyebrow": ("工会接待处 · 第一步", "Guild desk · Step 1"),
    "wizard.step1.title": ("冒险者，你要张贴什么委托？", "Adventurer, what contract are you posting?"),
    "wizard.step1.subtitle": ("主线提前规划有奖励。支线只填标题就能贴出去。", "Plan main quests ahead for a bonus. Side quests only need a title."),
    "wizard.main.title": ("主线任务", "Main quest"),
    "wizard.main.subtitle": ("计划委托", "Planned contract"),
    "wizard.main.detail": ("安排在未来完成。到了那天自动成为主线，报酬 +20%。", "Schedule it for later. On that day it becomes a main quest with +20%."),
    "wizard.side.title": ("支线任务", "Side quest"),
    "wizard.side.subtitle": ("临时委托", "Same-day contract"),
    "wizard.side.detail": ("今天突然冒出来的事。填个标题就能贴，报酬 -20%。", "A same-day surprise. Type a title and post — −20% reward."),
    "wizard.side.placeholder": ("例如：顺便倒个垃圾", "e.g. Take out the trash"),
    "wizard.step2.eyebrow": ("工会接待处 · 第二步", "Guild desk · Step 2"),
    "wizard.step2.title": ("这是长期委托，还是一次搞定？", "Is this a long-term contract, or a one-shot?"),
    "wizard.step2.subtitle": ("长期委托会按规律反复出现，单次委托只需要完成一次。", "Long-term contracts repeat. One-shot ones are completed once."),
    "wizard.long.title": ("长期任务", "Long-term"),
    "wizard.long.subtitle": ("周期委托", "Repeating contract"),
    "wizard.long.detail": ("每天阅读、每周健身，或在一段日期内持续推进。", "Daily reading, weekly workouts, or a stretch of dates."),
    "wizard.urgent.title": ("单次任务", "One-shot"),
    "wizard.urgent.subtitle": ("单次委托", "Complete once"),
    "wizard.urgent.detail": ("指定开始日期与当天截止时间，完成一次即可。", "Pick a start date and due time. Complete it once."),
    "wizard.field.title": ("委托名称", "Contract title"),
    "wizard.field.detail": ("描述（可选）", "Notes (optional)"),
    "wizard.notice": ("告示", "Notice"),
    "wizard.difficulty_section": ("任务难度", "Difficulty"),
    "wizard.skill_header": ("相关技能", "Related skills"),
    "wizard.skill_footer": ("可以选多项。完成后经验会平均分给所选技能。", "You can pick several. XP is split evenly on completion."),
    "wizard.skill_pick": ("相关技能（可选）", "Related skills (optional)"),
    "wizard.reward_section": ("预计报酬", "Estimated reward"),
    "wizard.type.side": ("支线 · 临时委托", "Side · same-day"),
    "wizard.type.urgent": ("主线 · 单次任务", "Main · one-shot"),
    "wizard.type.long": ("主线 · 长期委托", "Main · long-term"),
    "wizard.start_today_fixed": ("今天（支线固定）", "Today (side quests only)"),
    "wizard.start_date": ("开始日期", "Start date"),
    "wizard.due_time": ("截止时间", "Due time"),
    "wizard.schedule": ("排期", "Schedule"),
    "wizard.hint.side": ("回车即可张贴。当天临时委托报酬 -20%；提前规划主线才有加成。", "Press return to post. Same-day side quests pay −20%. Plan a main quest ahead for the bonus."),
    "wizard.hint.ahead": ("开始日在今天之后，将作为主线张贴，完成时 +20% 提前规划加成。", "A start date after today posts as a main quest with +20% planning bonus."),
    "wizard.hint.today_main": ("开始日是今天。仍会挂在主线栏，但按当天临时结算，报酬 -20%。想拿满加成，请改到明天。", "Start date is today. It stays on the main board but pays the same-day −20%. Move it to tomorrow for the full bonus."),
    "wizard.long_mode": ("排期方式", "Schedule mode"),
    "wizard.long_how": ("长期委托怎么排", "How to schedule the long-term quest"),
    "wizard.long_recurrence_footer": ("按规律自动生成实例，视同提前规划的主线。", "Instances generate automatically and count as planned main quests."),
    "wizard.long_range_footer": ("只张贴一条跨越多日的委托：从开始日挂到截止日，期间都会出现在任务栏上。", "Posts one spanning contract from start to due date. It stays on the board the whole time."),
    "wizard.set_end": ("设置结束日期", "Set end date"),
    "wizard.ends_on": ("结束于", "Ends on"),
    "wizard.until_when": ("持续到何时", "How long"),
    "wizard.no_end": ("不设结束日期就会一直按规律生成。", "With no end date, instances keep generating."),
    "wizard.end_date": ("截止日期", "End date"),
    "wizard.due_on_end": ("当天截止时间", "Due time that day"),
    "wizard.range_section": ("一段时间", "Date range"),
    "wizard.range_footer": ("委托会从开始日一直挂到截止日期。截止时间是截止日期当天的钟点。", "The contract stays from the start date through the due date. Due time is on the end day."),
    "wizard.base_reward": ("基础 %d EXP · %d 金币", "Base %d XP · %d gold"),

    # Planning calendar
    "planning.title": ("告示日历", "Board calendar"),
    "planning.which_day": ("查看哪天", "Which day"),
    "planning.custom_date": ("自选日期", "Pick a date"),
    "planning.target_day": ("目标日", "Target day"),
    "planning.day_quests": ("当天委托", "That day's contracts"),
    "planning.empty": ("这一天的告示板还是空的", "This day's board is empty"),
    "planning.repeat_preview": ("当天会自动生成的周期委托", "Repeating contracts that will generate"),
    "planning.repeat_footer": ("周期委托在当天开始时自动生成，视同提前规划的主线。", "Repeating contracts generate at day start and count as planned main quests."),
    "planning.hint.ahead": ("安排在未来的委托，到了那天会自动变成主线，并获得 +20% 提前规划加成。", "Future contracts become main quests that day, with +20% planning bonus."),
    "planning.hint.today": ("安排在今天的委托按当天临时结算，报酬 -20%。", "Contracts scheduled today pay the same-day −20% reward."),

    # Growth
    "growth.title": ("成长", "Growth"),
    "growth.view": ("视角", "View"),
    "growth.stats": ("属性", "Stats"),
    "growth.skills": ("技能", "Skills"),
    "growth.habits": ("习惯", "Habits"),
    "stat.philosophy": ("属性描述你正在成为怎样的人，技能描述你学会了什么。", "Stats describe who you are becoming. Skills describe what you have learned."),
    "stat.feeding": ("正在喂养这个属性的技能", "Skills feeding this stat"),
    "stat.feeding.empty": ("完成带有对应亲和度的技能任务，这个属性才会成长。幸运不能从这里训练。", "Complete quests with matching skill affinities to grow this stat. Luck cannot be trained here."),
    "lucky.today": ("今日命运：%@ · 经验与金币 %@", "Today's fortune: %@ · XP & gold %@"),
    "skill.empty.title": ("还没有技能", "No skills yet"),
    "skill.empty.message": ("技能占用栏位。开局有有限的栏位，升级后可以解锁更多。完成任务时把经验分配给它们。", "Skills take slots. You start with a few, and can unlock more by leveling up. Assign XP when you complete quests."),
    "skill.empty.action": ("创建技能", "Create skill"),
    "skill.unassigned": ("未分配属性", "Unassigned"),
    "skill.total_exp": ("总经验", "Total XP"),
    "skill.created": ("创建于", "Created"),
    "skill.affinity": ("属性亲和", "Stat affinity"),
    "skill.footer": ("完成任务时把经验分配给这个技能，它就会独立成长，并按亲和度喂养核心属性。幸运不能从技能训练。", "Assign quest XP to this skill and it grows on its own, feeding core stats by affinity. Luck cannot be trained from skills."),
    "skill.add": ("添加技能", "Add skill"),
    "skill.catalog": ("预设技能", "Presets"),
    "skill.custom": ("自定义", "Custom"),
    "skill.method": ("方式", "Method"),
    "skill.name_placeholder": ("例如 Origami、Archery", "e.g. Origami, Archery"),
    "skill.no_categories": ("目录里还没有类别", "No categories in the catalog"),
    "skill.affinity_footer": ("一个技能可以同时喂养多个核心属性，权重合计 100%。幸运不能从这里分配。", "A skill can feed several core stats. Weights must total 100%. Luck cannot be assigned here."),
    "skill.share_header": ("五个核心属性共用 100%", "Five core stats share 100%"),
    "skill.allocated": ("已分配 %d%%", "%d%% allocated"),
    "skill.no_share": ("还没有技能，先去成长页创建一个", "No skills yet. Create one in Growth first."),
    "skill.share_all": ("所有技能共用 100%", "All skills share 100%"),
    "skill.share_partial": ("经验分配", "XP share"),

    # Habits
    "habit.empty.title": ("还没有习惯", "No habits yet"),
    "habit.empty.message": ("阅读、喝水、运动、写日记……习惯是最稳定的经验来源。", "Reading, water, workouts, journaling — habits are the steadiest XP source."),
    "habit.empty.action": ("创建习惯", "Create habit"),
    "habit.new": ("新建习惯", "New habit"),
    "habit.name_placeholder": ("例如 阅读、喝水、冥想", "e.g. Reading, Water, Meditation"),
    "habit.icon_color": ("图标与颜色", "Icon & color"),
    "habit.daily_target": ("每日目标", "Daily target"),
    "habit.times_per_day": ("每天 %d 次", "%d times / day"),
    "habit.target_footer": ("奖励只在达成当日目标的那一次发放，所以把目标拆得更细不会拿到更多经验。", "Reward is granted only when the daily target is met, so splitting targets does not earn more XP."),
    "habit.reminder": ("提醒", "Reminder"),
    "habit.remind_daily": ("每天提醒", "Daily reminder"),
    "habit.time": ("时间", "Time"),
    "habit.days": ("天", "days"),
    "habit.best": ("最长连续 %d 天 · 累计 %d 次", "Best %d days · %d total"),
    "habit.last_30": ("最近 30 天", "Last 30 days"),
    "habit.times_value": ("%d 次", "%d times"),
    "habit.reminder_unset": ("未设置", "Not set"),
    "habit.check_again": ("今天再打一次卡", "Check in again today"),
    "habit.undo_today": ("撤销今天一次", "Undo one today"),
    "habit.fill_today": ("补满今天", "Fill today"),
    "habit.undo_once": ("撤销一次", "Undo one"),

    # Profile
    "profile.title": ("我的", "Me"),
    "profile.tab.overview": ("总览", "Overview"),
    "profile.tab.honors": ("荣誉", "Honors"),
    "profile.tab.shop": ("商店", "Shop"),
    "profile.character": ("角色数据", "Character"),
    "profile.days_played": ("累计天数", "Days played"),
    "profile.login_streak": ("连续登录", "Login streak"),
    "profile.login_streak_value": ("%d 天（最长 %d 天）", "%d days (best %d)"),
    "profile.quests_done": ("完成任务", "Quests completed"),
    "profile.main_side": ("主线 / 支线", "Main / side"),
    "profile.habit_checkins": ("习惯打卡", "Habit check-ins"),
    "profile.habit_checkins_value": ("%d 次", "%d times"),
    "profile.perfect": ("完美达成", "Perfect days"),
    "profile.perfect_value": ("%d 天", "%d days"),
    "profile.lifetime": ("累计获得", "Lifetime gain"),
    "profile.core_stats": ("核心属性", "Core stats"),
    "profile.lifetime_stats": ("生涯数据", "Lifetime"),
    "profile.best_streak": ("最佳连续", "Best streak"),
    "profile.main_quests": ("主线任务", "Main quests"),
    "profile.side_quests": ("支线任务", "Side quests"),
    "profile.habit_practice": ("日常修行", "Daily practice"),
    "profile.perfect_days": ("完美日", "Perfect days"),
    "profile.lifetime_exp": ("累计经验", "Cumulative XP"),
    "profile.lifetime_gold": ("累计金币", "Cumulative gold"),
    "profile.view_all": ("查看全部", "View all"),
    "profile.honors.empty.achievements": ("还没有成就进度", "No achievement progress yet"),
    "profile.honors.empty.titles": ("还没有称号", "No titles yet"),
    "profile.honors.empty.challenges": ("还没有挑战", "No challenges yet"),
    "profile.records": ("成长记录", "Progress"),
    "profile.achievements": ("成就", "Achievements"),
    "profile.titles": ("称号", "Titles"),
    "profile.challenges": ("挑战", "Challenges"),
    "profile.ledger": ("奖励流水", "Ledger"),
    "profile.shop": ("商店", "Shop"),
    "profile.settings": ("设置", "Settings"),

    "ledger.title": ("奖励流水", "Ledger"),
    "ledger.empty": ("还没有任何记录", "No records yet"),
    "ledger.reverted": ("已撤销", "Reverted"),

    "source.quest": ("任务", "Quest"),
    "source.habit": ("习惯", "Habit"),
    "source.challenge": ("挑战", "Challenge"),
    "source.achievement": ("成就", "Achievement"),
    "source.levelUp": ("升级", "Level up"),
    "source.streakBonus": ("连续奖励", "Streak bonus"),
    "source.purchase": ("购买", "Purchase"),
    "source.manual": ("手动调整", "Manual"),
    "source.recurringFinish": ("旅途收队", "Journey home"),

    "unlock.kind.achievement": ("成就", "Achievement"),
    "unlock.kind.title": ("称号", "Title"),
    "unlock.kind.challenge": ("挑战", "Challenge"),
    "unlock.unlocked": ("已解锁", "Unlocked"),
    "unlock.obtained": ("已获得", "Earned"),
    "unlock.locked": ("未解锁", "Locked"),
    "unlock.unlocked_banner": ("%@解锁：%@", "%@ unlocked: %@"),
    "title.none": ("不佩戴称号", "No title"),
    "title.empty": ("还没有称号，去完成成就吧", "No titles yet. Earn some achievements."),
    "title.equipped": ("佩戴中", "Equipped"),
    "title.equip": ("佩戴", "Equip"),
    "challenge.none": ("没有进行中的挑战", "No active challenges"),
    "challenge.ongoing": ("进行中", "In progress"),
    "challenge.footer": ("挑战是长期目标，进度由你的实际数据自动推导，不需要手动打勾。", "Challenges are long-term goals. Progress is derived from your real data — no manual checkmarks."),
    "challenge.completed": ("已完成", "Completed"),
    "challenge.custom": ("自定义挑战", "Custom challenge"),
    "challenge.name": ("挑战名称", "Challenge name"),
    "challenge.track": ("追踪什么", "What to track"),
    "challenge.any_skill": ("任意技能", "Any skill"),
    "challenge.any_habit": ("任意习惯", "Any habit"),
    "challenge.target": ("目标值", "Target"),
    "challenge.target_placeholder": ("目标", "Target"),
    "challenge.condition": ("达成条件", "Condition"),
    "challenge.condition_footer": ("挑战会持续对照你的真实数据自动判定，达成时自动结算奖励。", "The challenge watches your real data and pays out automatically when you hit the target."),
    "metric.totalQuestsCompleted": ("累计完成任务", "Quests completed"),
    "metric.totalMainQuestsCompleted": ("累计完成主线", "Main quests completed"),
    "metric.totalHabitCheckIns": ("累计打卡", "Habit check-ins"),
    "metric.bestLoginStreak": ("最长连续登录", "Best login streak"),
    "metric.playerLevel": ("玩家等级", "Player level"),
    "metric.totalStudyMinutes": ("累计学习时长", "Study time"),
    "metric.totalFocusMinutes": ("累计专注时长", "Focus time"),
    "metric.perfectDays": ("完美达成天数", "Perfect days"),
    "metric.skillLevel": ("指定技能等级", "Skill level"),
    "metric.habitStreak": ("指定习惯连续", "Habit streak"),
    "metric.recurringSeriesFinished": ("走完的远行", "Finished expeditions"),
    "metric.longestRecurringSeriesDays": ("最长一趟远行", "Longest expedition"),
    "metric.recurringJourneys": ("走过的旅途段", "Journey legs"),

    # Stats page
    "stats.title": ("统计", "Statistics"),
    "stats.range": ("范围", "Range"),
    "stats.range.day": ("日", "Day"),
    "stats.range.week": ("周", "Week"),
    "stats.range.month": ("月", "Month"),
    "stats.range.year": ("年", "Year"),
    "stats.range.all": ("全部", "All"),
    "stats.overview": ("概览", "Overview"),
    "stats.completion": ("完成率", "Completion"),
    "stats.quests_done": ("完成任务", "Quests"),
    "stats.habit_checkins": ("习惯打卡", "Habits"),
    "stats.exp_earned": ("获得 EXP", "XP earned"),
    "stats.gold_earned": ("获得 Gold", "Gold earned"),
    "stats.active_days": ("活跃天数", "Active days"),
    "stats.avg_hours": ("任务从创建到完成平均耗时 %.1f 小时", "Average %.1f hours from create to complete"),
    "stats.daily_gain": ("每日获得", "Daily gain"),
    "stats.daily_gain_sub": ("经验与金币的产出节奏", "XP and gold cadence"),
    "stats.no_data": ("这个区间还没有数据", "No data in this range"),
    "stats.chart.date": ("日期", "Date"),
    "stats.main_side": ("主线与支线", "Main vs side"),
    "stats.main_side_sub": ("规划带来的结构变化", "How planning shapes the mix"),
    "stats.main_count": ("主线 %d", "Main %d"),
    "stats.side_count": ("支线 %d", "Side %d"),
    "stats.skill_curve": ("技能成长曲线", "Skill growth"),
    "stats.no_skills": ("还没有技能", "No skills yet"),
    "stats.skill": ("技能", "Skill"),
    "stats.level": ("等级", "Level"),
    "stats.heatmap": ("完成热力图", "Completion heatmap"),
    "stats.heatmap_sub": ("最近 26 周", "Last 26 weeks"),
    "stats.less": ("少", "Less"),
    "stats.more": ("多", "More"),
    "stats.mix.healthy": ("大部分产出来自提前规划的主线，节奏很健康。", "Most output comes from planned main quests. Healthy pace."),
    "stats.mix.mixed": ("主线与支线各占一半，试着把更多事情提前一天安排。", "Main and side are even. Try planning more things a day ahead."),
    "stats.mix.side": ("几乎全是当天临时任务，奖励会少 20%。规划一下明天会立刻见效。", "Almost everything is same-day. Rewards take a −20% cut. Plan tomorrow and it pays off immediately."),

    # Shop
    "shop.title": ("商店", "Shop"),
    "shop.kind": ("分类", "Category"),
    "shop.theme": ("主题", "Theme"),
    "shop.avatarFrame": ("头像框", "Frame"),
    "shop.background": ("背景", "Background"),
    "shop.effect": ("特效", "Effect"),
    "shop.sound": ("音效", "Sound"),
    "shop.pet": ("宠物", "Pet"),
    "shop.consumable": ("道具", "Items"),
    "shop.use_ward": ("选择暂停日", "Pick a pause day"),
    "shop.pick_pause_day": ("暂停日期", "Pause date"),
    "shop.owned_count": ("持有 %d 张", "%d in bag"),
    "shop.shield_held": ("法术护盾尚未消耗，不能再买", "You already hold a spell shield"),
    "shop.shield_ready": ("护盾持有中", "Shield ready"),
    "shop.cannot_buy": ("无法购买", "Can't buy"),
    "shop.already_owned": ("已经拥有这件物品", "You already own this"),
    "shop.level_too_low": ("需要达到 Lv%d", "Requires Lv%d"),
    "shop.not_enough_gold": ("还差 %d 金币", "%d gold short"),
    "shop.buy_title": ("购买 %@", "Buy %@"),

    # Settings
    "settings.title": ("设置", "Settings"),
    "settings.language": ("语言", "Language"),
    "settings.language_footer": ("切换后界面立即更新。你自己起的任务、技能和习惯名称不会被翻译。", "The interface updates immediately. Names you typed for quests, skills, and habits stay as they are."),
    "settings.appearance": ("外观", "Appearance"),
    "settings.theme_mode": ("主题模式", "Appearance"),
    "settings.rpg_ui": ("RPG 风格界面", "RPG-styled UI"),
    "settings.color_theme": ("配色主题", "Color theme"),
    "settings.default_theme": ("默认", "Default"),
    "settings.time": ("时间", "Time"),
    "settings.day_start": ("一天从几点开始", "When the day starts"),
    "settings.carry_over": ("未完成的任务自动顺延", "Carry unfinished quests over"),
    "settings.time_footer": ("设为凌晨 4 点时，凌晨 1 点完成的任务仍然算作前一天。这个值会直接改变连续天数的统计口径，中途修改可能让某些连续记录看起来发生跳变。", "With a 4 AM day start, a 1 AM completion still counts as yesterday. This changes how streaks are counted; changing it mid-run can make streaks jump."),
    "settings.notifications": ("通知", "Notifications"),
    "settings.enable_notifications": ("启用本地通知", "Enable local notifications"),
    "settings.notifications_footer": (
        "只会在三种情况提醒：18 小时没有打开 App、超过 1 天没使用，以及任务截止前 1 小时。",
        "Reminders fire only after 18 hours away, after more than a day unused, and 1 hour before a quest is due."
    ),
    "settings.planning_reminder": ("明日规划提醒", "Tomorrow planning reminder"),
    "settings.reminder_time": ("提醒时间", "Reminder time"),
    "settings.bedtime": ("睡觉提醒", "Bedtime reminder"),
    "settings.bedtime_time": ("睡觉时间", "Bedtime"),
    "settings.request_permission": ("请求通知权限", "Request notification permission"),
    "settings.data": ("数据", "Data"),
    "settings.export_backup": ("导出完整备份（JSON）", "Export full backup (JSON)"),
    "settings.export_quests": ("导出任务（CSV）", "Export quests (CSV)"),
    "settings.export_daily": ("导出每日统计（CSV）", "Export daily stats (CSV)"),
    "settings.export_pdf": ("导出成长报告（PDF）", "Export growth report (PDF)"),
    "settings.restore": ("从备份恢复", "Restore from backup"),
    "settings.data_footer": ("恢复会先清空当前全部数据再写入备份内容，操作不可撤销。建议先导出一份当前备份。", "Restore wipes current data then writes the backup. This cannot be undone. Export a backup first."),
    "settings.testing": ("测试", "Testing"),
    "settings.shop_sandbox": ("解除商店限制并无限金币", "Unlock shop and infinite gold"),
    "settings.shop_sandbox_footer": ("仅用于测试。开启后商店不再检查等级，金币显示为无限，购买不扣真实余额。关闭后立即恢复原来的金币与解锁规则。", "For testing only. Shop ignores level gates, gold is treated as infinite, and purchases do not spend your real balance. Turning it off restores the original rules immediately."),
    "settings.diagnostics": ("配置诊断", "Config diagnostics"),
    "settings.about": ("关于", "About"),
    "settings.balance_version": ("平衡表版本", "Balance version"),
    "settings.rule_count": ("规则数量", "Rule count"),
    "settings.runtime": ("运行模式", "Runtime"),
    "settings.runtime.memory": ("内存（数据不会保留）", "In-memory (data will not persist)"),
    "settings.runtime.disk": ("本地持久化", "On-device persistence"),
    "settings.export_failed": ("导出失败：%@", "Export failed: %@"),
    "settings.restore_ok": ("恢复完成", "Restore complete"),
    "settings.restore_failed": ("恢复失败：%@", "Restore failed: %@"),
    "settings.account": ("账户", "Account"),
    "settings.reset": ("注销账户并清空存档", "Sign out and erase save"),
    "settings.reset_footer": ("会删除当前角色的全部进度、任务、技能和习惯，然后重新进入初始化流程。此操作不可撤销，建议先导出备份。", "Deletes this character's progress, quests, skills, and habits, then returns you to setup. This cannot be undone. Export a backup first."),
    "settings.reset.title": ("注销账户？", "Erase this save?"),
    "settings.reset.message": ("当前存档将被永久删除，你将以新的冒险者从头开始。", "This save will be permanently deleted. You will start over as a new adventurer."),
    "settings.reset.confirm": ("删除存档", "Delete save"),
    "settings.reset_failed": ("注销失败：%@", "Could not erase save: %@"),

    # Onboarding
    "onboarding.nav": ("冒险者登记", "Adventurer registry"),
    "onboarding.welcome": ("欢迎来到人生冒险", "Welcome to Life RPG"),
    "onboarding.step.title": ("称号", "Title"),
    "onboarding.step.skills": ("技能", "Skills"),
    "onboarding.title.subtitle": ("先给自己想一个冒险者称号，并选一个头像。称号是别人看到你时的名字，之后仍可更换。", "First, invent an adventurer title and pick an avatar. This is the name the world will know you by."),
    "onboarding.title.label": ("冒险者称号", "Adventurer title"),
    "onboarding.avatar.label": ("角色头像", "Character avatar"),
    "onboarding.avatar.subtitle": ("选一个预设形象，或从相册导入自己的照片。之后点头像仍可更换。", "Pick a preset look, or import a photo. You can change it later by tapping the avatar."),
    "avatar.presets": ("预设形象", "Preset looks"),
    "avatar.photo": ("相册", "Photos"),
    "avatar.camera": ("拍照", "Camera"),
    "avatar.edit": ("更换头像", "Change avatar"),
    "avatar.edit.title": ("角色头像", "Character avatar"),
    "onboarding.title.placeholder": ("例如：晨星旅人", "e.g. Dawn Traveler"),
    "onboarding.title.footer": ("最多 16 个字符。这是你的角色名，和之后解锁的佩戴称号不同。", "Up to 16 characters. This is your character name, separate from unlockable titles."),
    "onboarding.next": ("下一步", "Continue"),
    "onboarding.skills.hello": ("你好，%@", "Hello, %@"),
    "onboarding.skills.subtitle": ("从预设技能中挑选 0 到 %d 个你感兴趣的方向，也可以自定义。选定后将从零开始正式冒险。", "Pick 0 to %d skills from the catalog, or create your own. After this, the adventure starts from zero."),
    "onboarding.skills.selected": ("已选 %d / %d", "Selected %d / %d"),
    "onboarding.skills.count": ("已选 %d / %d 个技能", "%d / %d skills selected"),
    "onboarding.skills.custom": ("自定义技能", "Create a custom skill"),
    "onboarding.skills.custom_footer": ("自定义技能同样占用初始栏位。之后要学更多，需要升级解锁栏位，或先忘记一个技能。", "Custom skills also use a starting slot. Unlock more on level-up, or forget a skill later."),
    "onboarding.skills.full": ("初始栏位已经选满。去掉一个后才能再添加。", "Starting slots are full. Remove one to add another."),
    "onboarding.skills.skip_hint": ("一个都不选也可以。之后栏位有空时再学新技能。", "You can pick none and learn skills later when a slot is free."),
    "onboarding.start": ("开始冒险", "Begin adventure"),

    "tutorial.welcome.title": ("工会接待处", "Guild desk"),
    "tutorial.welcome.message": ("欢迎来到工会接待处！这里是你的冒险起点。我将引导你熟悉工会详情，并发布你的第一个任务。", "Welcome to the guild desk! This is where your adventure begins. I’ll show you around and help you post your first quest."),
    "tutorial.welcome.action": ("好的！", "Got it!"),
    "tutorial.tapPublishMain.title": ("发布主线", "Post a main quest"),
    "tutorial.tapPublishMain.message": ("点告示栏上的加号，开始贴主线。", "Tap the plus on the board to post a main quest."),
    "tutorial.pickMain.title": ("选择主线任务", "Choose main quest"),
    "tutorial.pickMain.message": ("点这张卡片，这里可以发布主线任务，安排未来要做的事情。", "Tap this card to post a main quest and plan something for later."),
    "tutorial.pickUrgent.title": ("先贴一张单次主线", "Post a one-shot first"),
    "tutorial.pickUrgent.message": ("点「单次任务」，这里可以发布一次性的任务。", "Tap One-shot to post a one-time quest."),
    "tutorial.fillMain.title": ("写下主线名称", "Name the main quest"),
    "tutorial.fillMain.message": ("输入明天要做的事，再点右上角「张贴」。", "Type tomorrow’s task, then tap Post at the top right."),
    "tutorial.tapPublishSide.title": ("再贴一张支线", "Post a side quest"),
    "tutorial.tapPublishSide.message": ("再点加号，贴一张今天的支线。", "Tap plus again to post a same-day side quest."),
    "tutorial.pickSide.title": ("选择支线任务", "Choose side quest"),
    "tutorial.pickSide.message": ("点这张卡片。支线只需要一个标题。用于记录当天的突发奇想", "Tap this card. Side quests only need a title — for same-day ideas that pop up."),
    "tutorial.fillSide.title": ("写下支线名称", "Name the side quest"),
    "tutorial.fillSide.message": ("输入标题后回车，或点右上角张贴。", "Type a title, then press return or tap Post."),
    "tutorial.goGrowth.title": ("去成长页", "Open Growth"),
    "tutorial.goGrowth.message": ("点底部「成长」，去立一条日常修行。", "Tap Growth at the bottom to add a daily practice."),
    "tutorial.pickHabits.title": ("打开习惯", "Open Habits"),
    "tutorial.pickHabits.message": ("点「习惯」这一栏。", "Tap the Habits tab."),
    "tutorial.tapAddHabit.title": ("新建日常修行", "Create a practice"),
    "tutorial.tapAddHabit.message": ("点加号或「创建习惯」。", "Tap plus or Create habit."),
    "tutorial.fillHabit.title": ("给修行起名", "Name the practice"),
    "tutorial.fillHabit.message": ("起个名字，再点右上角「保存」。", "Give it a name, then tap Save at the top right."),
    "tutorial.done.title": ("准备出发", "Ready to go"),
    "tutorial.done.message": ("这是只属于你的冒险，让我们开始吧！", "This adventure is yours. Let’s begin!"),
    "tutorial.done.action": ("开始冒险", "Start adventuring"),

    "skill.slots": ("技能栏位", "Skill slots"),
    "skill.slots.value": ("%d / %d", "%d / %d"),
    "skill.slots.hint": ("栏位满了之后，只能通过升级选择额外栏位，或删除已学技能来腾出位置。", "When slots are full, unlock more by leveling up or forget a skill to free one."),
    "skill.slots.full_hint": ("栏位已满。升级时选择额外栏位，或删除一个技能来学习新技能。", "Slots are full. Unlock more on level-up, or forget a skill to learn a new one."),
    "skill.slots.full": ("技能栏位已满（%d / %d）。先删除一个技能，或升级后选择额外栏位。", "Skill slots are full (%d / %d). Forget a skill, or unlock a slot on level-up."),
    "skill.quest_bonus": ("任务 +%d%%", "Quest +%d%%"),
    "skill.quest_bonus_label": ("关联任务奖励", "Quest reward bonus"),
    "skill.xp_bonus_label": ("技能经验增速", "Skill XP speed"),
    "skill.bonus_percent": ("+%d%%", "+%d%%"),
    "skill.delete.action": ("忘记这个技能", "Forget this skill"),
    "skill.delete.title": ("忘记技能？", "Forget this skill?"),
    "skill.delete.confirm": ("忘记并清空", "Forget"),
    "skill.delete.message": ("「%@」的 Lv%d 与全部经验会永久消失，栏位会空出来。此操作不可撤销。", "“%@” Lv%d and all of its XP will be erased, freeing the slot. This cannot be undone."),

    "stat.allocated": ("加点 +%d", "+%d allocated"),
    "stat.allocated_detail": ("加点 +%d · 训练等级 Lv%d", "+%d allocated · trained Lv%d"),
    "stat.effect": ("成长效果", "Growth effect"),
    "stat.effect.detail": ("匹配这个属性的技能经验加快 %d%%。", "Matching skills gain XP %d%% faster."),

    "levelup.title": ("升到 Lv%d", "Reached Lv%d"),
    "levelup.subtitle": ("金币已经入账。请再选一项额外奖励。", "Gold is already yours. Choose one extra reward."),
    "levelup.gold_already": ("金币奖励已发放", "Gold reward already granted"),
    "levelup.choice.stat": ("分配 1 点属性点", "Spend 1 stat point"),
    "levelup.choice.stat_detail": ("立刻加到五个核心属性之一，匹配技能的经验会涨得更快。", "Add it to one core stat. Matching skills will gain XP faster."),
    "levelup.choice.slot": ("解锁 1 个技能栏位", "Unlock 1 skill slot"),
    "levelup.choice.slot_detail": ("可掌握技能上限变为 %d。可以立刻学习，也可以留空。", "Skill cap becomes %d. Learn now or leave it empty."),
    "levelup.stat.current": ("当前 Lv%d", "Currently Lv%d"),
    "levelup.slot.unlocked": ("技能栏位已提升到 %d", "Skill cap is now %d"),
    "levelup.slot.followup": ("要现在学习新技能，还是把栏位留到以后？", "Learn a new skill now, or leave the slot empty?"),
    "levelup.slot.learn_now": ("立刻学习技能", "Learn a skill now"),
    "levelup.slot.later": ("稍后学习", "Learn later"),

    "reward.skill_level": ("技能等级 ×%.2f", "Skill level ×%.2f"),

    # Reminders / notifications
    "reminder.kind.quest": ("任务提醒", "Quest reminder"),
    "reminder.kind.habit": ("习惯提醒", "Habit reminder"),
    "reminder.kind.planning": ("明日规划提醒", "Planning reminder"),
    "reminder.kind.bedtime": ("睡觉提醒", "Bedtime reminder"),
    "reminder.kind.streak": ("连续签到提醒", "Streak reminder"),
    "reminder.kind.challenge": ("挑战提醒", "Challenge reminder"),
    "reminder.title.quest": ("任务到点了", "Quest is due"),
    "reminder.title.habit": ("该打卡了", "Time to check in"),
    "reminder.title.planning": ("规划明天的主线", "Plan tomorrow's main quests"),
    "reminder.title.bedtime": ("该休息了", "Time to rest"),
    "reminder.title.streak": ("别断了连续记录", "Don't break the streak"),
    "reminder.title.challenge": ("挑战进度检查", "Challenge check"),
    "notify.planning.body": ("花两分钟规划明天的主线，明天完成能多拿 20% 奖励", "Spend two minutes planning tomorrow's main quests for a +20% bonus"),
    "notify.bedtime.body": ("今天的冒险结束了，好好休息", "Today's adventure is over. Rest well."),
    "notify.guild.title": ("工会来信", "A note from the guild"),
    "notify.inactivity_18h.body": ("今天还没有来工会看看呢～任务都顺利完成了吗", "You haven't stopped by the guild today~ Did the quests go well?"),
    "notify.inactivity_1d.body": ("好久都没有来工会了呢～发布一些任务给明天的自己吧！", "It's been a while since you visited the guild~ Publish some quests for tomorrow's you!"),
    "notify.quest_due.body": ("这个任务要截止啦，快来完成领取报酬奖励吧！", "This quest is about to expire! Come finish it and claim your rewards!"),
    "alert.streak_shield.title": ("法术护盾生效", "Spell shield used"),
    "alert.streak_shield.body": ("你有一天没有打开应用，法术护盾已保护连胜。护盾已消耗，可再次购买保险卡。", "You missed a day. The spell shield protected your streak. You can buy another insurance card."),
    "fail.alert.title": ("任务失败", "Quests failed"),
    "fail.alert.message": ("以下任务因为逾期过久而失败：\n%@", "These quests failed after staying overdue too long:\n%@"),
    "fail.history.title": ("失败历史", "Failed history"),
    "fail.history.empty_title": ("还没有失败记录", "No failed quests"),
    "fail.history.empty": ("逾期过久的任务会记录在这里。", "Quests that stay overdue too long will appear here."),
    "fail.history.progress": ("进度 %d / %d", "Progress %d / %d"),
    "fail.history.failed_at": ("失败于 %@", "Failed %@"),
    "fail.history.period": ("%@ – %@", "%@ – %@"),
    "quest.remaining.week": ("本周还剩 %d 次", "%d left this week"),
    "quest.daily_cap.reached": ("今日次数已满", "Daily limit reached"),
    "quest.paused.today": ("今日进度已暂停", "Progress paused today"),
    "profile.failed_history": ("失败历史", "Failed history"),
    "profile.failed_history_count": ("%d 条记录", "%d records"),

    # Celebration / fortune events
    "celebrate.level_up": ("升级！Lv%d", "Level up! Lv%d"),
    "celebrate.named_level": ("%@ 升到 Lv%d", "%@ reached Lv%d"),
    "celebrate.gold": ("获得 %d 金币", "Gained %d gold"),
    "feedback.exp": ("+%d EXP", "+%d XP"),
    "feedback.gold": ("+%d G", "+%d G"),
    "fortune.event.lucky_day": ("幸运日 · %@", "Lucky Day · %@"),
    "fortune.event.bonus": ("经验与金币 %@", "XP & gold %@"),
    "fortune.event.bonus_gold": ("经验与金币 %@，额外 +%d 金币", "XP & gold %@, extra +%d gold"),
    "fortune.grew": ("幸运成长了", "Luck grew"),
    "fortune.level_up": ("幸运升到 Lv%d", "Luck reached Lv%d"),
    "fortune.xp": ("幸运 +%d EXP", "Luck +%d XP"),
    "reward.level_title": ("升级到 Lv%d", "Reached Lv%d"),
    "reward.level_breakdown": ("升级奖励 %d G", "Level-up reward %d G"),
    "reward.base": ("基础 %.0f", "Base %.0f"),
    "reward.duration": ("时长 ×%.2f", "Duration ×%.2f"),
    "reward.streak": ("连续 ×%.2f", "Streak ×%.2f"),

    # Config issues
    "config.missing": ("找不到配置文件 %@.json，已回退到内置默认值", "Missing %@.json, fell back to built-in defaults"),
    "config.parse": ("配置文件 %@.json 解析失败：%@", "Failed to parse %@.json: %@"),

    # Export
    "export.quests.header": ("日期,标题,类型,状态,难度,优先级,预计分钟,标签,完成时间,是否延期", "Date,Title,Type,Status,Difficulty,Priority,Minutes,Tags,Completed,Overdue"),
    "export.daily.header": ("日期,获得EXP,获得Gold,计划任务,完成任务,主线完成,支线完成,习惯打卡,习惯目标,完成率,专注分钟", "Date,XP,Gold,Planned,Completed,Main,Side,Habit check-ins,Habit targets,Completion,Focus minutes"),
    "export.pdf.title": ("Life RPG 成长报告", "Life RPG growth report"),
    "export.pdf.character": ("角色", "Character"),
    "export.pdf.nickname": ("昵称：%@", "Name: %@"),
    "export.pdf.level": ("等级：Lv%d（%d/%d EXP）", "Level: Lv%d (%d/%d XP)"),
    "export.pdf.gold": ("金币：%d", "Gold: %d"),
    "export.pdf.streak": ("连续登录：%d 天（最长 %d 天）", "Login streak: %d days (best %d)"),
    "export.pdf.days": ("累计天数：%d", "Days played: %d"),
    "export.pdf.quests": ("任务", "Quests"),
    "export.pdf.quests_done": ("累计完成：%d（主线 %d / 支线 %d）", "Completed: %d (main %d / side %d)"),
    "export.pdf.habits": ("习惯打卡：%d 次", "Habit check-ins: %d"),
    "export.pdf.perfect": ("完美达成天数：%d", "Perfect days: %d"),
    "export.pdf.skills": ("技能", "Skills"),
    "export.pdf.stats": ("统计", "Stats"),
    "export.pdf.records": ("有记录天数：%d，其中活跃 %d 天", "Recorded days: %d, active %d"),
    "export.pdf.lifetime": ("累计获得：%d EXP / %d Gold", "Lifetime: %d XP / %d Gold"),
    "export.pdf.exported": ("导出于 %@", "Exported %@"),

    # Core stats
    "stat.body.title": ("身体力", "Body"),
    "stat.mind.title": ("认知力", "Mind"),
    "stat.life.title": ("生活力", "Life"),
    "stat.social.title": ("社交力", "Social"),
    "stat.creation.title": ("创造力", "Creation"),
    "stat.body.summary": ("健康、体能、耐力与身体活动能力", "Health, fitness, endurance, and physical capability"),
    "stat.mind.summary": ("学习、理解、记忆、分析与知识积累", "Learning, reasoning, memory, and knowledge"),
    "stat.life.summary": ("管理时间、习惯、环境与日常事务的能力", "Managing time, habits, environment, and daily affairs"),
    "stat.social.summary": ("沟通、合作、表达与建立关系", "Communication, cooperation, expression, and relationships"),
    "stat.creation.summary": ("想象、设计、表达并把想法做成作品", "Imagination, design, expression, and making things"),
    "stat.body.definition": ("身体力代表身体健康、体能、力量、耐力、协调性以及身体活动能力。", "Body represents physical health, fitness, strength, endurance, coordination, and physical capability."),
    "stat.mind.definition": ("认知力代表学习、理解、记忆、分析、推理和知识积累能力。", "Mind represents the ability to learn, understand, remember, analyze, reason, and acquire knowledge."),
    "stat.life.definition": ("生活力代表一个人管理时间、习惯、环境、资源以及日常事务，并持续改善生活状态的综合能力。", "Life represents the ability to manage time, habits, environment, resources, and daily affairs, and to keep improving everyday living."),
    "stat.social.definition": ("社交力代表沟通、理解、合作、表达以及建立和维护人际关系的能力。", "Social represents the ability to communicate, understand, cooperate, express, and build relationships."),
    "stat.creation.definition": ("创造力代表想象、设计、表达以及把想法转化为实际作品的能力。", "Creation represents the ability to imagine, design, express, and turn ideas into something new."),
    "stat.lucky.title": ("幸运", "Lucky"),
    "stat.lucky.summary": ("命运的眷顾。不能训练，只能被惊喜点亮。", "Fortune's favor. It cannot be trained, only sparked as a surprise."),
    "stat.lucky.definition": ("幸运不是现实能力，而是命运对你的眷顾程度。无法主动分配，也无法直接训练。", "Luck is not a real-world skill. It is how much fate favors you. You cannot assign it or train it."),

    "stat.body.domain.0": ("力量", "Strength"),
    "stat.body.domain.1": ("耐力", "Endurance"),
    "stat.body.domain.2": ("心肺", "Cardio"),
    "stat.body.domain.3": ("柔韧", "Flexibility"),
    "stat.body.domain.4": ("协调", "Coordination"),
    "stat.body.domain.5": ("运动能力", "Athletics"),
    "stat.body.domain.6": ("身体健康", "Health"),
    "stat.mind.domain.0": ("学习", "Learning"),
    "stat.mind.domain.1": ("知识", "Knowledge"),
    "stat.mind.domain.2": ("逻辑", "Logic"),
    "stat.mind.domain.3": ("记忆", "Memory"),
    "stat.mind.domain.4": ("语言", "Language"),
    "stat.mind.domain.5": ("研究", "Research"),
    "stat.mind.domain.6": ("分析", "Analysis"),
    "stat.mind.domain.7": ("阅读", "Reading"),
    "stat.life.domain.0": ("自律", "Discipline"),
    "stat.life.domain.1": ("时间管理", "Time management"),
    "stat.life.domain.2": ("组织管理", "Organization"),
    "stat.life.domain.3": ("日常生活", "Daily living"),
    "stat.life.domain.4": ("财务管理", "Finance"),
    "stat.life.domain.5": ("独立生活", "Independence"),
    "stat.social.domain.0": ("沟通", "Communication"),
    "stat.social.domain.1": ("表达", "Expression"),
    "stat.social.domain.2": ("倾听", "Listening"),
    "stat.social.domain.3": ("合作", "Cooperation"),
    "stat.social.domain.4": ("领导", "Leadership"),
    "stat.social.domain.5": ("谈判", "Negotiation"),
    "stat.social.domain.6": ("社交", "Socializing"),
    "stat.social.domain.7": ("人际关系", "Relationships"),
    "stat.creation.domain.0": ("艺术", "Art"),
    "stat.creation.domain.1": ("设计", "Design"),
    "stat.creation.domain.2": ("写作", "Writing"),
    "stat.creation.domain.3": ("音乐", "Music"),
    "stat.creation.domain.4": ("游戏开发", "Game development"),
    "stat.creation.domain.5": ("摄影", "Photography"),
    "stat.creation.domain.6": ("视频", "Video"),
    "stat.creation.domain.7": ("手工", "Craft"),

    # Fortune
    "fortune.fortune_1.name": ("小吉", "Fortune I"),
    "fortune.fortune_2.name": ("中吉", "Fortune II"),
    "fortune.fortune_3.name": ("大吉", "Fortune III"),
    "fortune.fortune_4.name": ("天命", "Fortune IV"),

    # Modifiers
    "modifier.planned_ahead.label": ("提前规划", "Planned ahead"),
    "modifier.same_day.label": ("当天临时", "Same day"),
    "modifier.on_time.label": ("按时完成", "On time"),
    "modifier.overdue.label": ("延期完成", "Overdue"),
    "modifier.five_star.label": ("五星任务", "Five-star"),
    "modifier.consecutive.label": ("连续完成", "Streak"),

    # Skill categories
    "skill.category.fitness": ("体能", "Fitness"),
    "skill.category.knowledge": ("知识", "Knowledge"),
    "skill.category.language": ("语言", "Language"),
    "skill.category.discipline": ("自律", "Discipline"),
    "skill.category.time": ("时间", "Time"),
    "skill.category.organization": ("组织", "Organization"),
    "skill.category.daily_living": ("日常", "Daily living"),
    "skill.category.finance": ("财务", "Finance"),
    "skill.category.independence": ("独立", "Independence"),
    "skill.category.communication": ("沟通", "Communication"),
    "skill.category.leadership": ("领导", "Leadership"),
    "skill.category.art": ("艺术", "Art"),
    "skill.category.design": ("设计", "Design"),
    "skill.category.media": ("影像", "Media"),
    "skill.category.craft": ("手作", "Craft"),
}

SKILLS = {
    "running": ("跑步", "Running"),
    "swimming": ("游泳", "Swimming"),
    "walking": ("步行", "Walking"),
    "cycling": ("骑行", "Cycling"),
    "hiking": ("徒步", "Hiking"),
    "strength_training": ("力量训练", "Strength Training"),
    "yoga": ("瑜伽", "Yoga"),
    "dancing": ("舞蹈", "Dancing"),
    "martial_arts": ("武术", "Martial Arts"),
    "reading": ("阅读", "Reading"),
    "studying": ("学习", "Studying"),
    "programming": ("编程", "Programming"),
    "mathematics": ("数学", "Mathematics"),
    "japanese": ("日语", "Japanese"),
    "english": ("英语", "English"),
    "research": ("研究", "Research"),
    "writing": ("写作", "Writing"),
    "habit_building": ("习惯养成", "Habit Building"),
    "planning": ("规划", "Planning"),
    "task_management": ("任务管理", "Task Management"),
    "cooking": ("烹饪", "Cooking"),
    "cleaning": ("打扫", "Cleaning"),
    "budgeting": ("记账", "Budgeting"),
    "conversation": ("交谈", "Conversation"),
    "public_speaking": ("演讲", "Public Speaking"),
    "listening": ("倾听", "Listening"),
    "negotiation": ("谈判", "Negotiation"),
    "teamwork": ("协作", "Teamwork"),
    "leadership": ("领导力", "Leadership"),
    "drawing": ("绘画", "Drawing"),
    "music": ("音乐", "Music"),
    "photography": ("摄影", "Photography"),
    "design": ("设计", "Design"),
    "game_development": ("游戏开发", "Game Development"),
    "video_editing": ("视频剪辑", "Video Editing"),
    "crafting": ("手工", "Crafting"),
}

SHOP = {
    "theme_default": ("起始之地", "Starting Land", "冒险者工会的默认装潢：浅蓝雾气与金线边框。", "Guild hall mist and gold trim."),
    "theme_forest": ("翡翠密林", "Jade Forest", "给首页铺上林雾与落叶，卡片改成苔藓金边。", "Forest haze, falling leaves, mossy gold cards."),
    "theme_ember": ("余烬熔炉", "Ember Forge", "底部燃起余烬光晕，适合夜间赶工的冒险者。", "Ember glow along the bottom of the screen."),
    "theme_midnight": ("午夜星轨", "Midnight Orbit", "深靛夜空与缓慢闪烁的星点。", "Deep indigo sky with drifting stars."),
    "theme_sakura": ("落樱庭院", "Sakura Court", "粉色花瓣缓缓飘过冒险者面板。", "Pink petals drift across the boards."),
    "theme_gold": ("黄金王座", "Golden Throne", "传说级金辉：更厚的饰边与暖色光晕。", "Legendary gold trim and a warm halo."),
    "frame_bronze": ("青铜边框", "Bronze Frame", "厚实的单层金属环，套在头像外侧。", "A solid bronze ring around your avatar."),
    "frame_silver": ("白银边框", "Silver Frame", "双层银环，内侧有一圈高光。", "A double silver ring with an inner gleam."),
    "frame_gold": ("黄金边框", "Gold Frame", "金环外带柔光，头像会微微发亮。", "A glowing gold ring around your avatar."),
    "frame_mythic": ("秘境边框", "Mythic Frame", "圆形秘纹光环，沿边缓慢流转渐变。", "A circular mythic halo with a drifting gradient."),
    "bg_parchment": ("羊皮卷", "Parchment", "给今日冒险铺一层手札纸纹，与主题叠加。", "Journal paper grain layered over your theme."),
    "bg_aurora": ("极光", "Aurora", "北境光带在首页后方缓慢流动。", "Northern lights drift behind today's board."),
    "fx_levelup_burst": ("升级光爆", "Level Burst", "在默认升级光效之上，再爆出更密的全屏光粒。", "Adds a denser full-screen burst on top of the default level-up glow."),
    "fx_complete_spark": ("完成火花", "Completion Spark", "在行内跳字之上，再叠一层全屏火花与金币光点。", "Adds a full-screen spark shower on top of the inline +XP / +G."),
    "sfx_classic": ("经典音效包", "Classic SFX", "完成、升级、购买时播放复古 RPG 提示音。", "Classic RPG cues on complete, level-up, and buy."),
    "pet_slime": ("史莱姆", "Slime", "蹲在首页右下角，跟着你轻轻弹跳。", "Bounces in the corner of Home."),
    "pet_owl": ("学者猫头鹰", "Scholar Owl", "夜间的首页伙伴，会在角落打盹。", "A late-night companion on Home."),
    "consumable_ward": ("完美防御力场", "Perfect Ward", "请假卡。购买后放入背包，选择一天冻结全部任务进度，周期不会因此提前失败。", "Leave card. Pick a day to freeze all quest progress so periods don't fail early."),
    "consumable_shield": ("法术护盾", "Spell Shield", "保险卡。漏登一天时自动保护登录连胜，持有上限一张，触发后可再买。", "Insurance card. Protects your login streak for one missed day. Can't stack."),
}

UNLOCKS = {
    "ach_first_quest": ("第一步", "First Step", "完成你的第一个任务", "Complete your first quest"),
    "ach_quest_10": ("十战", "Tenfold", "累计完成 10 个任务", "Complete 10 quests"),
    "ach_quest_25": ("廿五征", "Proven", "累计完成 25 个任务", "Complete 25 quests"),
    "ach_quest_50": ("半百", "Half Century", "累计完成 50 个任务", "Complete 50 quests"),
    "ach_quest_100": ("百战", "Centurion", "累计完成 100 个任务", "Complete 100 quests"),
    "ach_quest_500": ("五百炼", "Five Hundred", "累计完成 500 个任务", "Complete 500 quests"),
    "ach_quest_1000": ("千锤百炼", "Tempered", "累计完成 1000 个任务", "Complete 1000 quests"),
    "ach_main_1": ("接下契约", "First Contract", "完成你的第一个主线任务", "Complete your first main quest"),
    "ach_main_10": ("十成契约", "Ten Contracts", "累计完成 10 个主线任务", "Complete 10 main quests"),
    "ach_main_50": ("主线推进者", "Mainline", "累计完成 50 个主线任务", "Complete 50 main quests"),
    "ach_side_10": ("支线猎手", "Side Hunter", "累计完成 10 个支线任务", "Complete 10 side quests"),
    "ach_habit_1": ("初次打卡", "First Check-in", "完成第一次习惯打卡", "Complete your first habit check-in"),
    "ach_habit_10": ("十日之功", "Ten Check-ins", "累计打卡 10 次", "Check in 10 times"),
    "ach_habit_50": ("五十成习", "Fifty Habits", "累计打卡 50 次", "Check in 50 times"),
    "ach_habit_100": ("习惯的力量", "Habit Power", "累计打卡 100 次", "Check in 100 times"),
    "ach_login_3": ("三日之约", "Three Days", "连续登录 3 天", "Log in 3 days in a row"),
    "ach_login_7": ("一周不辍", "Week Unbroken", "连续登录 7 天", "Log in 7 days in a row"),
    "ach_login_30": ("月度坚守", "Monthly Vigil", "连续登录 30 天", "Log in 30 days in a row"),
    "ach_login_100": ("百日之约", "Hundred Days", "连续登录 100 天", "Log in 100 days in a row"),
    "ach_player_5": ("启程", "Set Forth", "玩家等级达到 Lv5", "Reach player Lv5"),
    "ach_player_10": ("崭露头角", "Rising", "玩家等级达到 Lv10", "Reach player Lv10"),
    "ach_player_25": ("初露锋芒", "First Edge", "玩家等级达到 Lv25", "Reach player Lv25"),
    "ach_player_50": ("五十重楼", "Fiftieth Floor", "玩家等级达到 Lv50", "Reach player Lv50"),
    "ach_skill_10": ("入门", "Initiate", "任意技能达到 Lv10", "Any skill reaches Lv10"),
    "ach_skill_50": ("专精", "Specialist", "任意技能达到 Lv50", "Any skill reaches Lv50"),
    "ach_skill_100": ("宗师", "Grandmaster", "任意技能达到 Lv100", "Any skill reaches Lv100"),
    "ach_focus_10h": ("十小时深潜", "Ten-Hour Dive", "累计专注 10 小时", "Focus for 10 hours"),
    "ach_focus_100h": ("百小时法则", "100-Hour Rule", "累计专注 100 小时", "Focus for 100 hours"),
    "ach_study_10h": ("初学乍练", "First Lectures", "累计学习 10 小时", "Study for 10 hours"),
    "ach_early_bird": ("破晓", "Daybreak", "在早上 6 点前完成一个任务", "Complete a quest before 6 AM"),
    "ach_night_owl": ("深夜行者", "Night Walker", "在凌晨 1 点后完成一个任务", "Complete a quest after 1 AM"),
    "ach_perfect_1": ("完美一日", "Perfect Day", "完成一个完成率 100% 的日子", "One day at 100% completion"),
    "ach_perfect_10": ("完美主义", "Perfectionist", "累计 10 个完成率 100% 的日子", "10 days at 100% completion"),
    "ach_days_14": ("两周冒险", "Two Weeks", "累计冒险 14 天", "Adventure for 14 days"),
    "ach_gold_1000": ("小金库", "First Fortune", "累计获得 1000 金币", "Earn 1000 gold"),
    "ach_quest_200": ("铁血远征", "Iron March", "累计完成 200 个任务", "Complete 200 quests"),
    "ach_side_50": ("密林猎影", "Shadow Hunt", "累计完成 50 个支线任务", "Complete 50 side quests"),
    "ach_main_25": ("誓约之证", "Oathbound", "累计完成 25 个主线任务", "Complete 25 main quests"),
    "ach_main_100": ("屠龙凯旋", "Dragonfall", "累计完成 100 个主线任务", "Complete 100 main quests"),
    "ach_habit_365": ("岁岁苦行", "Year of Asceticism", "累计打卡 365 次", "Check in 365 times"),
    "ach_login_14": ("十四守夜", "Fortnight Vigil", "连续登录 14 天", "Log in 14 days in a row"),
    "ach_login_365": ("不灭之火", "Eternal Flame", "连续登录 365 天", "Log in 365 days in a row"),
    "ach_player_30": ("江湖扬名", "Renowned", "玩家等级达到 Lv30", "Reach player Lv30"),
    "ach_player_75": ("七重天阙", "Seventh Heaven", "玩家等级达到 Lv75", "Reach player Lv75"),
    "ach_player_100": ("封神", "Ascension", "玩家等级达到 Lv100", "Reach player Lv100"),
    "ach_skill_25": ("小成之境", "Adept Realm", "任意技能达到 Lv25", "Any skill reaches Lv25"),
    "ach_skill_75": ("大成之境", "Master Realm", "任意技能达到 Lv75", "Any skill reaches Lv75"),
    "ach_focus_50h": ("入定", "Entering Trance", "累计专注 50 小时", "Focus for 50 hours"),
    "ach_study_20h": ("启智开卷", "Awakened Lore", "累计学习 20 小时", "Study for 20 hours"),
    "ach_study_50h": ("寒窗五十", "Fifty Hours of Lore", "累计学习 50 小时", "Study for 50 hours"),
    "ach_gold_5000": ("金库守卫", "Vault Keeper", "累计获得 5000 金币", "Earn 5000 gold"),
    "ach_gold_10000": ("万金领主", "Treasure Lord", "累计获得 10000 金币", "Earn 10000 gold"),
    "ach_exp_10000": ("万灵觉醒", "Soul Awakening", "累计获得 10000 经验", "Earn 10000 EXP"),
    "ach_days_30": ("满月远征", "Moon Cycle", "累计冒险 30 天", "Adventure for 30 days"),
    "ach_days_100": ("百日远征", "Hundred-Day March", "累计冒险 100 天", "Adventure for 100 days"),
    "ach_perfect_30": ("圣洁三十", "Thirty Sacred Days", "累计 30 个完成率 100% 的日子", "30 days at 100% completion"),
    "ach_collector_10": ("功勋拾遗", "First Honors", "解锁 10 个成就", "Unlock 10 achievements"),
    "title_novice": ("初心者", "Novice", "完成第一个任务", "Complete your first quest"),
    "title_apprentice": ("学徒", "Apprentice", "累计完成 10 个任务", "Complete 10 quests"),
    "title_adventurer": ("冒险者", "Adventurer", "累计完成 50 个任务", "Complete 50 quests"),
    "title_sprout": ("新芽", "Sprout", "玩家等级达到 Lv5", "Reach player Lv5"),
    "title_keeper": ("守约者", "Oathkeeper", "连续登录 7 天", "Log in 7 days in a row"),
    "title_disciplined": ("自律者", "Disciplined", "累计打卡 50 次", "Check in 50 times"),
    "title_planner": ("谋士", "Strategist", "累计完成 10 个主线任务", "Complete 10 main quests"),
    "title_ranger": ("游侠", "Ranger", "累计完成 10 个支线任务", "Complete 10 side quests"),
    "title_focused": ("凝神者", "Deep Focus", "累计专注 10 小时", "Focus for 10 hours"),
    "title_guardian": ("守护者", "Guardian", "连续登录 30 天", "Log in 30 days in a row"),
    "title_champion": ("冠军", "Champion", "玩家等级达到 Lv50", "Reach player Lv50"),
    "title_alchemist": ("炼金师", "Alchemist", "累计获得 1000 金币", "Earn 1000 gold"),
    "title_programmer": ("代码行者", "Code Walker", "编程技能达到 Lv20", "Programming reaches Lv20"),
    "title_scholar": ("学者", "Scholar", "累计学习 50 小时", "Study for 50 hours"),
    "title_warrior": ("武者", "Warrior", "力量训练技能达到 Lv20", "Strength Training reaches Lv20"),
    "title_artist": ("画师", "Artist", "绘画技能达到 Lv20", "Drawing reaches Lv20"),
    "title_reader": ("书虫", "Bookworm", "阅读技能达到 Lv10", "Reading reaches Lv10"),
    "title_chef": ("掌厨", "Chef", "烹饪技能达到 Lv20", "Cooking reaches Lv20"),
    "title_musician": ("乐师", "Musician", "音乐技能达到 Lv20", "Music reaches Lv20"),
    "title_runner": ("疾行者", "Runner", "跑步技能达到 Lv20", "Running reaches Lv20"),
    "title_craftsman": ("工匠", "Artisan", "手工技能达到 Lv20", "Crafting reaches Lv20"),
    "title_leader": ("领袖", "Leader", "领导力技能达到 Lv20", "Leadership reaches Lv20"),
    "title_orator": ("演说家", "Orator", "演讲技能达到 Lv20", "Public Speaking reaches Lv20"),
    "title_explorer": ("探索者", "Explorer", "连续登录 100 天", "Log in 100 days in a row"),
    "title_night_owl": ("夜枭", "Night Owl", "在凌晨完成任务", "Complete a quest after midnight"),
    "title_early_bird": ("晨雀", "Early Bird", "在清晨完成任务", "Complete a quest in the morning"),
    "title_legend": ("传说", "Legend", "玩家等级达到 Lv60", "Reach player Lv60"),
    "title_squire": ("侍从", "Squire", "累计完成 25 个任务", "Complete 25 quests"),
    "title_veteran": ("老兵", "Veteran", "累计完成 100 个任务", "Complete 100 quests"),
    "title_hero": ("英雄", "Hero", "玩家等级达到 Lv30", "Reach player Lv30"),
    "title_knight": ("骑士", "Knight", "累计完成 25 个主线任务", "Complete 25 main quests"),
    "title_paladin": ("圣骑士", "Paladin", "累计 30 个完成率 100% 的日子", "30 days at 100% completion"),
    "title_mage": ("法师", "Mage", "累计学习 20 小时", "Study for 20 hours"),
    "title_archmage": ("大法师", "Archmage", "累计学习 200 小时", "Study for 200 hours"),
    "title_monk": ("武僧", "Monk", "累计打卡 365 次", "Check in 365 times"),
    "title_assassin": ("刺客", "Assassin", "累计完成 50 个支线任务", "Complete 50 side quests"),
    "title_sage": ("贤者", "Sage", "解锁 20 个成就", "Unlock 20 achievements"),
    "title_immortal": ("不朽者", "Immortal", "连续登录 365 天", "Log in 365 days in a row"),
    "title_merchant": ("行商", "Merchant", "累计获得 5000 金币", "Earn 5000 gold"),
    "title_mythic": ("神话", "Mythic", "玩家等级达到 Lv100", "Reach player Lv100"),
    "title_scribe": ("书记官", "Scribe", "写作技能达到 Lv20", "Writing reaches Lv20"),
    "title_swordsman": ("剑士", "Blademaster", "武术技能达到 Lv20", "Martial Arts reaches Lv20"),
    "title_mystic": ("修士", "Mystic", "瑜伽技能达到 Lv20", "Yoga reaches Lv20"),
    "title_timekeeper": ("时之守望", "Timekeeper", "累计专注 50 小时", "Focus for 50 hours"),
    "title_dragonslayer": ("屠龙者", "Dragonslayer", "累计完成 100 个主线任务", "Complete 100 main quests"),
    "chal_read_100_days": ("连续阅读 100 天", "Read 100 Days", "保持阅读习惯连续 100 天", "Keep a reading streak of 100 days"),
    "chal_study_100h": ("完成 100 小时学习", "Study 100 Hours", "累计学习时长达到 100 小时", "Accumulate 100 hours of study"),
    "chal_quest_365": ("一年 365 个任务", "365 Quests", "累计完成 365 个任务", "Complete 365 quests"),
    "chal_fitness_lv30": ("健身达人", "Fitness Ace", "力量训练技能达到 Lv30", "Strength Training reaches Lv30"),
    "chal_habit_1000": ("千次打卡", "Thousand Check-ins", "累计打卡 1000 次", "Check in 1000 times"),
    "chal_focus_200h": ("二百时冥想", "Two Hundred Hours", "累计专注 200 小时，完成长线冥想试炼", "Focus for 200 hours to finish the meditation trial"),
    "chal_perfect_50": ("五十完璧", "Fifty Sacred Days", "累计 50 个完成率 100% 的日子", "50 days at 100% completion"),
    "chal_login_180": ("半年守夜", "Half-Year Vigil", "连续登录 180 天", "Log in 180 days in a row"),
    "chal_main_80": ("王都远征", "March on the Capital", "累计完成 80 个主线任务", "Complete 80 main quests"),
    "chal_player_80": ("问鼎八十", "Eightieth Ascent", "玩家等级达到 Lv80", "Reach player Lv80"),
    "chal_gold_20000": ("巨龙宝库", "Dragon Hoard", "累计获得 20000 金币", "Earn 20000 gold"),
    "chal_skill_80": ("登峰造极", "Peak Mastery", "任意技能达到 Lv80", "Any skill reaches Lv80"),
    "chal_days_365": ("一年冒险", "A Year of Adventure", "累计冒险 365 天", "Adventure for 365 days"),
    "chal_archmage": ("大法师试炼", "Archmage Trial", "累计学习 200 小时", "Study for 200 hours"),
    "chal_code_lv40": ("代码圣殿", "Code Sanctum", "编程技能达到 Lv40", "Programming reaches Lv40"),
    "ach_series_first": ("初履征途", "First Leg", "走完第一段周期旅途", "Finish your first period journey"),
    "ach_series_7d": ("初程归途", "Short Return", "结束一趟至少 7 天的远行", "Come home from an expedition of 7 days"),
    "ach_series_30d": ("月路归客", "Moon Road", "结束一趟至少 30 天的远行", "Come home from an expedition of 30 days"),
    "ach_series_100d": ("百日行记", "Hundred-Day Chronicle", "结束一趟至少 100 天的远行", "Come home from an expedition of 100 days"),
    "ach_series_365d": ("岁旅成册", "Yearlong Road", "结束一趟至少 365 天的远行", "Come home from an expedition of 365 days"),
    "ach_series_3": ("三段行纪", "Three Legs", "累计走完 3 段周期旅途", "Finish 3 period journeys"),
    "ach_series_10": ("十驿行囊", "Ten Stations", "累计走完 10 段周期旅途", "Finish 10 period journeys"),
    "title_oathcloser": ("旅人", "Wayfarer", "走完第一段周期旅途", "Finish your first period journey"),
    "title_campaigner": ("月下旅人", "Moon Traveler", "结束一趟至少 30 天的远行", "Come home from an expedition of 30 days"),
    "title_legend_oath": ("行记客", "Chronicler", "结束一趟至少 100 天的远行", "Come home from an expedition of 100 days"),
    "title_eternal_oath": ("岁路人", "Yearfarer", "结束一趟至少 365 天的远行", "Come home from an expedition of 365 days"),
    "title_closer": ("行纪者", "Road Scribe", "累计走完 3 段周期旅途", "Finish 3 period journeys"),
    "title_contract_master": ("十程旅者", "Ten-Road Traveler", "累计走完 10 段周期旅途", "Finish 10 period journeys"),
    "chal_series_365": ("环岁远征", "Circumyear Expedition", "结束一趟至少 365 天的远行", "Come home from an expedition of 365 days"),
    "chal_series_5": ("五段旅途", "Five Legs", "累计走完 5 段周期旅途", "Finish 5 period journeys"),
}


def main() -> None:
    table = dict(STRINGS)
    for sid, (zh, en) in SKILLS.items():
        table[f"skill.{sid}.name"] = (zh, en)
    for sid, (zh_name, en_name, zh_detail, en_detail) in SHOP.items():
        table[f"shop.{sid}.name"] = (zh_name, en_name)
        table[f"shop.{sid}.detail"] = (zh_detail, en_detail)
    for sid, (zh_name, en_name, zh_detail, en_detail) in UNLOCKS.items():
        table[f"unlock.{sid}.name"] = (zh_name, en_name)
        table[f"unlock.{sid}.detail"] = (zh_detail, en_detail)

    OUT.mkdir(parents=True, exist_ok=True)
    zh = {k: v[0] for k, v in table.items()}
    en = {k: v[1] for k, v in table.items()}
    for name, data in (("zh-Hans.json", zh), ("en.json", en)):
        path = OUT / name
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        print(f"wrote {path} ({len(data)} keys)")


if __name__ == "__main__":
    main()
